/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) FR_cost_y_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[26] = {22, 1, 0, 22, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21};
static const casadi_int casadi_s1[19] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[57] = {53, 1, 0, 53, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52};
static const casadi_int casadi_s4[40] = {36, 1, 0, 36, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35};
static const casadi_int casadi_s5[96] = {37, 36, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 26, 34, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 15, 16, 17, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 15, 18, 19, 20, 21, 22, 23, 24, 16, 18, 19, 20, 21, 22, 23, 24, 17, 18, 19, 20, 21, 22, 23, 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
static const casadi_int casadi_s6[3] = {36, 0, 0};

/* FR_cost_y_fun_jac_ut_xt:(i0[22],i1[15],i2[],i3[],i4[53])->(o0[36],o1[37x36,57nz],o2[36x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a1=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a1;
  a2=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a2;
  a3=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][3]=a3;
  a4=arg[0]? arg[0][8] : 0;
  if (res[0]!=0) res[0][4]=a4;
  a5=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][5]=a5;
  a6=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][6]=a6;
  a6=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][7]=a6;
  a6=arg[0]? arg[0][12] : 0;
  if (res[0]!=0) res[0][8]=a6;
  a6=arg[0]? arg[0][13] : 0;
  if (res[0]!=0) res[0][9]=a6;
  a6=arg[0]? arg[0][14] : 0;
  if (res[0]!=0) res[0][10]=a6;
  a6=arg[0]? arg[0][15] : 0;
  if (res[0]!=0) res[0][11]=a6;
  a6=arg[0]? arg[0][16] : 0;
  if (res[0]!=0) res[0][12]=a6;
  a6=arg[0]? arg[0][17] : 0;
  if (res[0]!=0) res[0][13]=a6;
  a6=arg[0]? arg[0][18] : 0;
  if (res[0]!=0) res[0][14]=a6;
  a6=arg[0]? arg[0][19] : 0;
  if (res[0]!=0) res[0][15]=a6;
  a6=arg[0]? arg[0][20] : 0;
  if (res[0]!=0) res[0][16]=a6;
  a6=arg[0]? arg[0][21] : 0;
  if (res[0]!=0) res[0][17]=a6;
  a6=-2.5000000000000000e-01;
  a7=1.;
  a8=2.;
  a9=arg[0]? arg[0][5] : 0;
  a10=casadi_sq(a9);
  a11=arg[0]? arg[0][4] : 0;
  a12=casadi_sq(a11);
  a10=(a10+a12);
  a10=(a8*a10);
  a10=(a7-a10);
  a12=cos(a4);
  a13=(a10*a12);
  a14=arg[0]? arg[0][6] : 0;
  a14=(a8*a14);
  a15=(a14*a11);
  a16=arg[0]? arg[0][3] : 0;
  a17=(a9*a16);
  a17=(a8*a17);
  a15=(a15+a17);
  a17=cos(a3);
  a18=(a15*a17);
  a19=(a11*a16);
  a19=(a8*a19);
  a20=(a14*a9);
  a19=(a19-a20);
  a20=sin(a3);
  a21=(a19*a20);
  a18=(a18-a21);
  a21=sin(a4);
  a22=(a18*a21);
  a13=(a13-a22);
  a22=sin(a5);
  a23=(a13*a22);
  a24=(a10*a21);
  a25=(a18*a12);
  a24=(a24+a25);
  a25=cos(a5);
  a26=(a24*a25);
  a23=(a23+a26);
  a23=(a6*a23);
  a26=(a6*a24);
  a27=-8.3000000000000004e-02;
  a28=(a19*a17);
  a29=(a15*a20);
  a28=(a28+a29);
  a28=(a27*a28);
  a29=2.3990000000000000e-01;
  a30=(a29*a10);
  a31=-5.0999999999999997e-02;
  a32=(a31*a19);
  a30=(a30+a32);
  a30=(a30+a0);
  a28=(a28+a30);
  a26=(a26+a28);
  a23=(a23+a26);
  a26=arg[4]? arg[4][0] : 0;
  a23=(a23*a26);
  if (res[0]!=0) res[0][18]=a23;
  a23=(a14*a9);
  a28=(a16*a11);
  a28=(a8*a28);
  a23=(a23+a28);
  a28=(a23*a12);
  a30=(a9*a11);
  a30=(a8*a30);
  a0=(a14*a16);
  a30=(a30-a0);
  a0=(a30*a17);
  a32=casadi_sq(a9);
  a33=casadi_sq(a16);
  a32=(a32+a33);
  a32=(a8*a32);
  a32=(a7-a32);
  a33=(a32*a20);
  a0=(a0-a33);
  a33=(a0*a21);
  a28=(a28-a33);
  a33=(a28*a22);
  a34=(a23*a21);
  a35=(a0*a12);
  a34=(a34+a35);
  a35=(a34*a25);
  a33=(a33+a35);
  a33=(a6*a33);
  a35=(a6*a34);
  a36=(a32*a17);
  a37=(a30*a20);
  a36=(a36+a37);
  a36=(a27*a36);
  a37=(a29*a23);
  a38=(a31*a32);
  a37=(a37+a38);
  a37=(a37+a1);
  a36=(a36+a37);
  a35=(a35+a36);
  a33=(a33+a35);
  a33=(a33*a26);
  if (res[0]!=0) res[0][19]=a33;
  a33=(a16*a9);
  a33=(a8*a33);
  a35=(a14*a11);
  a33=(a33-a35);
  a35=(a33*a12);
  a36=casadi_sq(a11);
  a37=casadi_sq(a16);
  a36=(a36+a37);
  a36=(a8*a36);
  a36=(a7-a36);
  a37=(a36*a17);
  a1=(a14*a16);
  a38=(a11*a9);
  a38=(a8*a38);
  a1=(a1+a38);
  a38=(a1*a20);
  a37=(a37-a38);
  a38=(a37*a21);
  a35=(a35-a38);
  a38=(a35*a22);
  a39=(a33*a21);
  a40=(a37*a12);
  a39=(a39+a40);
  a40=(a39*a25);
  a38=(a38+a40);
  a38=(a6*a38);
  a40=(a6*a39);
  a41=(a1*a17);
  a42=(a36*a20);
  a41=(a41+a42);
  a41=(a27*a41);
  a42=(a29*a33);
  a43=(a31*a1);
  a42=(a42+a43);
  a42=(a42+a2);
  a41=(a41+a42);
  a40=(a40+a41);
  a38=(a38+a40);
  a38=(a38*a26);
  if (res[0]!=0) res[0][20]=a38;
  a38=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][21]=a38;
  a38=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][22]=a38;
  a38=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][23]=a38;
  a38=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][24]=a38;
  a38=arg[1]? arg[1][4] : 0;
  if (res[0]!=0) res[0][25]=a38;
  a38=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][26]=a38;
  a38=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][27]=a38;
  a38=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][28]=a38;
  a38=arg[1]? arg[1][8] : 0;
  if (res[0]!=0) res[0][29]=a38;
  a38=arg[1]? arg[1][9] : 0;
  if (res[0]!=0) res[0][30]=a38;
  a38=arg[1]? arg[1][10] : 0;
  if (res[0]!=0) res[0][31]=a38;
  a38=arg[1]? arg[1][11] : 0;
  if (res[0]!=0) res[0][32]=a38;
  a38=arg[1]? arg[1][12] : 0;
  if (res[0]!=0) res[0][33]=a38;
  a38=arg[1]? arg[1][13] : 0;
  if (res[0]!=0) res[0][34]=a38;
  a38=arg[1]? arg[1][14] : 0;
  if (res[0]!=0) res[0][35]=a38;
  if (res[1]!=0) res[1][0]=a7;
  if (res[1]!=0) res[1][1]=a7;
  if (res[1]!=0) res[1][2]=a7;
  if (res[1]!=0) res[1][3]=a7;
  if (res[1]!=0) res[1][4]=a7;
  if (res[1]!=0) res[1][5]=a7;
  if (res[1]!=0) res[1][6]=a7;
  if (res[1]!=0) res[1][7]=a7;
  if (res[1]!=0) res[1][8]=a7;
  if (res[1]!=0) res[1][9]=a7;
  if (res[1]!=0) res[1][10]=a7;
  if (res[1]!=0) res[1][11]=a7;
  if (res[1]!=0) res[1][12]=a7;
  if (res[1]!=0) res[1][13]=a7;
  if (res[1]!=0) res[1][14]=a7;
  if (res[1]!=0) res[1][15]=a7;
  if (res[1]!=0) res[1][16]=a7;
  if (res[1]!=0) res[1][17]=a7;
  if (res[1]!=0) res[1][18]=a26;
  a38=(a8*a9);
  a40=(a17*a38);
  a41=(a8*a11);
  a42=(a20*a41);
  a40=(a40-a42);
  a42=(a12*a40);
  a2=(a25*a42);
  a40=(a21*a40);
  a40=(a22*a40);
  a2=(a2-a40);
  a2=(a6*a2);
  a42=(a6*a42);
  a40=(a17*a41);
  a38=(a20*a38);
  a40=(a40+a38);
  a40=(a27*a40);
  a41=(a31*a41);
  a40=(a40+a41);
  a42=(a42+a40);
  a2=(a2+a42);
  a2=(a26*a2);
  if (res[1]!=0) res[1][19]=a2;
  a2=(a17*a14);
  a42=(a8*a16);
  a40=(a20*a42);
  a2=(a2-a40);
  a40=(a12*a2);
  a41=(a11+a11);
  a41=(a8*a41);
  a38=(a21*a41);
  a40=(a40-a38);
  a38=(a25*a40);
  a43=(a12*a41);
  a2=(a21*a2);
  a43=(a43+a2);
  a43=(a22*a43);
  a38=(a38-a43);
  a38=(a6*a38);
  a40=(a6*a40);
  a43=(a17*a42);
  a2=(a20*a14);
  a43=(a43+a2);
  a43=(a27*a43);
  a42=(a31*a42);
  a41=(a29*a41);
  a42=(a42-a41);
  a43=(a43+a42);
  a40=(a40+a43);
  a38=(a38+a40);
  a38=(a26*a38);
  if (res[1]!=0) res[1][20]=a38;
  a38=(a8*a16);
  a40=(a17*a38);
  a43=(a20*a14);
  a40=(a40+a43);
  a43=(a12*a40);
  a42=(a9+a9);
  a42=(a8*a42);
  a41=(a21*a42);
  a43=(a43-a41);
  a41=(a25*a43);
  a2=(a12*a42);
  a40=(a21*a40);
  a2=(a2+a40);
  a2=(a22*a2);
  a41=(a41-a2);
  a41=(a6*a41);
  a43=(a6*a43);
  a38=(a20*a38);
  a2=(a17*a14);
  a38=(a38-a2);
  a38=(a27*a38);
  a42=(a29*a42);
  a2=(a31*a14);
  a42=(a42+a2);
  a38=(a38-a42);
  a43=(a43+a38);
  a41=(a41+a43);
  a41=(a26*a41);
  if (res[1]!=0) res[1][21]=a41;
  a41=(a8*a11);
  a43=(a17*a41);
  a38=(a8*a9);
  a42=(a20*a38);
  a43=(a43+a42);
  a42=(a12*a43);
  a2=(a25*a42);
  a43=(a21*a43);
  a43=(a22*a43);
  a2=(a2-a43);
  a2=(a6*a2);
  a42=(a6*a42);
  a41=(a20*a41);
  a43=(a17*a38);
  a41=(a41-a43);
  a41=(a27*a41);
  a38=(a31*a38);
  a41=(a41-a38);
  a42=(a42+a41);
  a2=(a2+a42);
  a2=(a26*a2);
  if (res[1]!=0) res[1][22]=a2;
  a2=sin(a3);
  a42=(a15*a2);
  a3=cos(a3);
  a41=(a19*a3);
  a42=(a42+a41);
  a41=(a21*a42);
  a41=(a22*a41);
  a42=(a12*a42);
  a38=(a25*a42);
  a41=(a41-a38);
  a41=(a6*a41);
  a15=(a15*a3);
  a19=(a19*a2);
  a15=(a15-a19);
  a15=(a27*a15);
  a42=(a6*a42);
  a15=(a15-a42);
  a41=(a41+a15);
  a41=(a26*a41);
  if (res[1]!=0) res[1][23]=a41;
  a41=cos(a4);
  a15=(a10*a41);
  a4=sin(a4);
  a42=(a18*a4);
  a15=(a15-a42);
  a42=(a25*a15);
  a10=(a10*a4);
  a18=(a18*a41);
  a10=(a10+a18);
  a10=(a22*a10);
  a42=(a42-a10);
  a42=(a6*a42);
  a15=(a6*a15);
  a42=(a42+a15);
  a42=(a26*a42);
  if (res[1]!=0) res[1][24]=a42;
  a42=cos(a5);
  a13=(a13*a42);
  a5=sin(a5);
  a24=(a24*a5);
  a13=(a13-a24);
  a13=(a6*a13);
  a13=(a26*a13);
  if (res[1]!=0) res[1][25]=a13;
  if (res[1]!=0) res[1][26]=a26;
  a13=(a8*a11);
  a24=(a12*a13);
  a15=(a16+a16);
  a15=(a8*a15);
  a10=(a20*a15);
  a18=(a17*a14);
  a10=(a10-a18);
  a18=(a21*a10);
  a24=(a24-a18);
  a24=(a22*a24);
  a18=(a21*a13);
  a10=(a12*a10);
  a18=(a18+a10);
  a10=(a25*a18);
  a24=(a24+a10);
  a24=(a6*a24);
  a18=(a6*a18);
  a13=(a29*a13);
  a10=(a31*a15);
  a13=(a13-a10);
  a15=(a17*a15);
  a10=(a20*a14);
  a15=(a15+a10);
  a15=(a27*a15);
  a13=(a13-a15);
  a18=(a18+a13);
  a24=(a24+a18);
  a24=(a26*a24);
  if (res[1]!=0) res[1][27]=a24;
  a24=(a8*a16);
  a18=(a12*a24);
  a13=(a8*a9);
  a15=(a17*a13);
  a10=(a21*a15);
  a18=(a18-a10);
  a18=(a22*a18);
  a10=(a21*a24);
  a15=(a12*a15);
  a10=(a10+a15);
  a15=(a25*a10);
  a18=(a18+a15);
  a18=(a6*a18);
  a10=(a6*a10);
  a13=(a20*a13);
  a13=(a27*a13);
  a24=(a29*a24);
  a13=(a13+a24);
  a10=(a10+a13);
  a18=(a18+a10);
  a18=(a26*a18);
  if (res[1]!=0) res[1][28]=a18;
  a18=(a12*a14);
  a10=(a8*a11);
  a13=(a17*a10);
  a24=(a9+a9);
  a24=(a8*a24);
  a15=(a20*a24);
  a13=(a13+a15);
  a15=(a21*a13);
  a18=(a18-a15);
  a18=(a22*a18);
  a15=(a21*a14);
  a13=(a12*a13);
  a15=(a15+a13);
  a13=(a25*a15);
  a18=(a18+a13);
  a18=(a6*a18);
  a15=(a6*a15);
  a10=(a20*a10);
  a13=(a17*a24);
  a10=(a10-a13);
  a10=(a27*a10);
  a13=(a29*a14);
  a24=(a31*a24);
  a13=(a13-a24);
  a10=(a10+a13);
  a15=(a15+a10);
  a18=(a18+a15);
  a18=(a26*a18);
  if (res[1]!=0) res[1][29]=a18;
  a18=(a8*a9);
  a15=(a12*a18);
  a10=(a8*a16);
  a13=(a17*a10);
  a24=(a21*a13);
  a15=(a15+a24);
  a15=(a22*a15);
  a24=(a21*a18);
  a13=(a12*a13);
  a24=(a24-a13);
  a13=(a25*a24);
  a15=(a15+a13);
  a15=(a6*a15);
  a24=(a6*a24);
  a18=(a29*a18);
  a10=(a20*a10);
  a10=(a27*a10);
  a18=(a18-a10);
  a24=(a24+a18);
  a15=(a15+a24);
  a15=(a26*a15);
  if (res[1]!=0) res[1][30]=a15;
  a15=(a30*a2);
  a24=(a32*a3);
  a15=(a15+a24);
  a24=(a21*a15);
  a24=(a22*a24);
  a15=(a12*a15);
  a18=(a25*a15);
  a24=(a24-a18);
  a24=(a6*a24);
  a30=(a30*a3);
  a32=(a32*a2);
  a30=(a30-a32);
  a30=(a27*a30);
  a15=(a6*a15);
  a30=(a30-a15);
  a24=(a24+a30);
  a24=(a26*a24);
  if (res[1]!=0) res[1][31]=a24;
  a24=(a23*a41);
  a30=(a0*a4);
  a24=(a24-a30);
  a30=(a25*a24);
  a23=(a23*a4);
  a0=(a0*a41);
  a23=(a23+a0);
  a23=(a22*a23);
  a30=(a30-a23);
  a30=(a6*a30);
  a24=(a6*a24);
  a30=(a30+a24);
  a30=(a26*a30);
  if (res[1]!=0) res[1][32]=a30;
  a28=(a28*a42);
  a34=(a34*a5);
  a28=(a28-a34);
  a28=(a6*a28);
  a28=(a26*a28);
  if (res[1]!=0) res[1][33]=a28;
  if (res[1]!=0) res[1][34]=a26;
  a28=(a8*a9);
  a34=(a12*a28);
  a30=(a16+a16);
  a30=(a8*a30);
  a24=(a17*a30);
  a23=(a20*a14);
  a24=(a24+a23);
  a23=(a21*a24);
  a34=(a34+a23);
  a34=(a22*a34);
  a23=(a21*a28);
  a24=(a12*a24);
  a23=(a23-a24);
  a24=(a25*a23);
  a34=(a34+a24);
  a34=(a6*a34);
  a23=(a6*a23);
  a24=(a17*a14);
  a30=(a20*a30);
  a24=(a24-a30);
  a24=(a27*a24);
  a28=(a29*a28);
  a30=(a31*a14);
  a28=(a28+a30);
  a24=(a24+a28);
  a23=(a23+a24);
  a34=(a34+a23);
  a34=(a26*a34);
  if (res[1]!=0) res[1][35]=a34;
  a34=(a11+a11);
  a34=(a8*a34);
  a23=(a17*a34);
  a9=(a8*a9);
  a24=(a20*a9);
  a23=(a23+a24);
  a24=(a21*a23);
  a28=(a12*a14);
  a24=(a24-a28);
  a24=(a22*a24);
  a28=(a21*a14);
  a23=(a12*a23);
  a28=(a28+a23);
  a23=(a25*a28);
  a24=(a24-a23);
  a24=(a6*a24);
  a23=(a17*a9);
  a34=(a20*a34);
  a23=(a23-a34);
  a23=(a27*a23);
  a9=(a31*a9);
  a14=(a29*a14);
  a9=(a9-a14);
  a23=(a23+a9);
  a28=(a6*a28);
  a23=(a23-a28);
  a24=(a24+a23);
  a24=(a26*a24);
  if (res[1]!=0) res[1][36]=a24;
  a24=(a8*a16);
  a23=(a12*a24);
  a28=(a8*a11);
  a9=(a20*a28);
  a14=(a21*a9);
  a23=(a23+a14);
  a23=(a22*a23);
  a14=(a21*a24);
  a9=(a12*a9);
  a14=(a14-a9);
  a9=(a25*a14);
  a23=(a23+a9);
  a23=(a6*a23);
  a14=(a6*a14);
  a9=(a17*a28);
  a9=(a27*a9);
  a24=(a29*a24);
  a28=(a31*a28);
  a24=(a24+a28);
  a9=(a9+a24);
  a14=(a14+a9);
  a23=(a23+a14);
  a23=(a26*a23);
  if (res[1]!=0) res[1][37]=a23;
  a16=(a8*a16);
  a20=(a20*a16);
  a23=(a21*a20);
  a8=(a8*a11);
  a11=(a12*a8);
  a23=(a23-a11);
  a23=(a22*a23);
  a11=(a21*a8);
  a20=(a12*a20);
  a11=(a11+a20);
  a20=(a25*a11);
  a23=(a23-a20);
  a23=(a6*a23);
  a17=(a17*a16);
  a17=(a27*a17);
  a31=(a31*a16);
  a29=(a29*a8);
  a31=(a31-a29);
  a17=(a17+a31);
  a11=(a6*a11);
  a17=(a17-a11);
  a23=(a23+a17);
  a23=(a26*a23);
  if (res[1]!=0) res[1][38]=a23;
  a23=(a36*a2);
  a17=(a1*a3);
  a23=(a23+a17);
  a21=(a21*a23);
  a21=(a22*a21);
  a12=(a12*a23);
  a23=(a25*a12);
  a21=(a21-a23);
  a21=(a6*a21);
  a36=(a36*a3);
  a1=(a1*a2);
  a36=(a36-a1);
  a27=(a27*a36);
  a12=(a6*a12);
  a27=(a27-a12);
  a21=(a21+a27);
  a21=(a26*a21);
  if (res[1]!=0) res[1][39]=a21;
  a21=(a33*a41);
  a27=(a37*a4);
  a21=(a21-a27);
  a25=(a25*a21);
  a33=(a33*a4);
  a37=(a37*a41);
  a33=(a33+a37);
  a22=(a22*a33);
  a25=(a25-a22);
  a25=(a6*a25);
  a21=(a6*a21);
  a25=(a25+a21);
  a25=(a26*a25);
  if (res[1]!=0) res[1][40]=a25;
  a35=(a35*a42);
  a39=(a39*a5);
  a35=(a35-a39);
  a6=(a6*a35);
  a26=(a26*a6);
  if (res[1]!=0) res[1][41]=a26;
  if (res[1]!=0) res[1][42]=a7;
  if (res[1]!=0) res[1][43]=a7;
  if (res[1]!=0) res[1][44]=a7;
  if (res[1]!=0) res[1][45]=a7;
  if (res[1]!=0) res[1][46]=a7;
  if (res[1]!=0) res[1][47]=a7;
  if (res[1]!=0) res[1][48]=a7;
  if (res[1]!=0) res[1][49]=a7;
  if (res[1]!=0) res[1][50]=a7;
  if (res[1]!=0) res[1][51]=a7;
  if (res[1]!=0) res[1][52]=a7;
  if (res[1]!=0) res[1][53]=a7;
  if (res[1]!=0) res[1][54]=a7;
  if (res[1]!=0) res[1][55]=a7;
  if (res[1]!=0) res[1][56]=a7;
  return 0;
}

CASADI_SYMBOL_EXPORT int FR_cost_y_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int FR_cost_y_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int FR_cost_y_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FR_cost_y_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int FR_cost_y_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FR_cost_y_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void FR_cost_y_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void FR_cost_y_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int FR_cost_y_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int FR_cost_y_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real FR_cost_y_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FR_cost_y_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FR_cost_y_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FR_cost_y_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FR_cost_y_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int FR_cost_y_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
