/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) front_cost_y_e_fun_jac_ut_xt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[55] = {51, 1, 0, 51, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50};
static const casadi_int casadi_s3[34] = {30, 1, 0, 30, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29};
static const casadi_int casadi_s4[114] = {25, 30, 0, 1, 2, 3, 7, 11, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 41, 49, 57, 65, 73, 81, 0, 1, 2, 3, 4, 5, 6, 3, 4, 5, 6, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 0, 3, 4, 5, 6, 7, 8, 9, 1, 3, 4, 5, 6, 7, 8, 9, 2, 3, 4, 5, 6, 7, 8, 9, 0, 3, 4, 5, 6, 10, 11, 12, 1, 3, 4, 5, 6, 10, 11, 12, 2, 3, 4, 5, 6, 10, 11, 12};
static const casadi_int casadi_s5[3] = {30, 0, 0};

/* front_cost_y_e_fun_jac_ut_xt:(i0[25],i1[],i2[],i3[],i4[51])->(o0[30],o1[25x30,81nz],o2[30x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a9;
  a0=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a1=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a1;
  a2=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a2;
  a3=2.;
  a4=arg[4]? arg[4][37] : 0;
  a5=arg[0]? arg[0][3] : 0;
  a6=(a4*a5);
  a7=arg[0]? arg[0][6] : 0;
  a8=arg[4]? arg[4][34] : 0;
  a9=(a7*a8);
  a6=(a6-a9);
  a9=arg[4]? arg[4][36] : 0;
  a10=arg[0]? arg[0][4] : 0;
  a11=(a9*a10);
  a12=arg[4]? arg[4][35] : 0;
  a13=arg[0]? arg[0][5] : 0;
  a14=(a12*a13);
  a11=(a11-a14);
  a6=(a6+a11);
  a11=(a3*a6);
  a14=2.2204460492503131e-16;
  a6=(a6+a14);
  a15=casadi_sq(a6);
  a16=(a4*a10);
  a17=(a7*a12);
  a16=(a16-a17);
  a17=(a8*a13);
  a18=(a9*a5);
  a17=(a17-a18);
  a16=(a16+a17);
  a17=(a16+a14);
  a18=casadi_sq(a17);
  a15=(a15+a18);
  a18=(a4*a13);
  a19=(a7*a9);
  a18=(a18-a19);
  a19=(a12*a5);
  a20=(a8*a10);
  a19=(a19-a20);
  a18=(a18+a19);
  a14=(a18+a14);
  a19=casadi_sq(a14);
  a15=(a15+a19);
  a19=sqrt(a15);
  a20=(a4*a7);
  a21=(a8*a5);
  a22=(a12*a10);
  a21=(a21+a22);
  a22=(a9*a13);
  a21=(a21+a22);
  a20=(a20+a21);
  a21=atan2(a19,a20);
  a22=(a11*a21);
  a22=(a22/a19);
  if (res[0]!=0) res[0][3]=a22;
  a16=(a3*a16);
  a23=(a16*a21);
  a23=(a23/a19);
  if (res[0]!=0) res[0][4]=a23;
  a18=(a3*a18);
  a24=(a18*a21);
  a24=(a24/a19);
  if (res[0]!=0) res[0][5]=a24;
  a25=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][6]=a25;
  a26=arg[0]? arg[0][8] : 0;
  if (res[0]!=0) res[0][7]=a26;
  a27=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][8]=a27;
  a28=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][9]=a28;
  a29=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][10]=a29;
  a30=arg[0]? arg[0][12] : 0;
  if (res[0]!=0) res[0][11]=a30;
  a31=arg[0]? arg[0][13] : 0;
  if (res[0]!=0) res[0][12]=a31;
  a31=arg[0]? arg[0][14] : 0;
  if (res[0]!=0) res[0][13]=a31;
  a31=arg[0]? arg[0][15] : 0;
  if (res[0]!=0) res[0][14]=a31;
  a31=arg[0]? arg[0][16] : 0;
  if (res[0]!=0) res[0][15]=a31;
  a31=arg[0]? arg[0][17] : 0;
  if (res[0]!=0) res[0][16]=a31;
  a31=arg[0]? arg[0][18] : 0;
  if (res[0]!=0) res[0][17]=a31;
  a31=arg[0]? arg[0][19] : 0;
  if (res[0]!=0) res[0][18]=a31;
  a31=arg[0]? arg[0][20] : 0;
  if (res[0]!=0) res[0][19]=a31;
  a31=arg[0]? arg[0][21] : 0;
  if (res[0]!=0) res[0][20]=a31;
  a31=arg[0]? arg[0][22] : 0;
  if (res[0]!=0) res[0][21]=a31;
  a31=arg[0]? arg[0][23] : 0;
  if (res[0]!=0) res[0][22]=a31;
  a31=arg[0]? arg[0][24] : 0;
  if (res[0]!=0) res[0][23]=a31;
  a31=-2.5000000000000000e-01;
  a32=1.;
  a33=casadi_sq(a13);
  a34=casadi_sq(a10);
  a35=(a33+a34);
  a35=(a3*a35);
  a35=(a32-a35);
  a36=cos(a26);
  a37=(a35*a36);
  a7=(a3*a7);
  a38=(a7*a10);
  a39=(a13*a5);
  a39=(a3*a39);
  a39=(a38+a39);
  a40=cos(a25);
  a41=(a39*a40);
  a42=(a10*a5);
  a42=(a3*a42);
  a43=(a7*a13);
  a42=(a42-a43);
  a25=sin(a25);
  a44=(a42*a25);
  a41=(a41-a44);
  a26=sin(a26);
  a44=(a41*a26);
  a37=(a37-a44);
  a44=sin(a27);
  a45=(a37*a44);
  a46=(a35*a26);
  a47=(a41*a36);
  a46=(a46+a47);
  a27=cos(a27);
  a47=(a46*a27);
  a45=(a45+a47);
  a45=(a31*a45);
  a47=(a31*a46);
  a48=-8.6800000000000002e-02;
  a49=(a42*a40);
  a50=(a39*a25);
  a51=(a49+a50);
  a51=(a48*a51);
  a52=2.4070000000000000e-01;
  a53=(a52*a35);
  a54=-5.0999999999999997e-02;
  a55=(a54*a42);
  a55=(a53+a55);
  a55=(a55+a0);
  a51=(a51+a55);
  a47=(a47+a51);
  a45=(a45+a47);
  if (res[0]!=0) res[0][24]=a45;
  a45=(a5*a10);
  a45=(a3*a45);
  a43=(a43+a45);
  a45=(a43*a36);
  a47=(a13*a10);
  a47=(a3*a47);
  a51=(a7*a5);
  a47=(a47-a51);
  a55=(a47*a40);
  a56=casadi_sq(a5);
  a33=(a33+a56);
  a33=(a3*a33);
  a33=(a32-a33);
  a57=(a33*a25);
  a55=(a55-a57);
  a57=(a55*a26);
  a45=(a45-a57);
  a57=(a45*a44);
  a58=(a43*a26);
  a59=(a55*a36);
  a58=(a58+a59);
  a59=(a58*a27);
  a57=(a57+a59);
  a57=(a31*a57);
  a59=(a31*a58);
  a60=(a33*a40);
  a61=(a47*a25);
  a62=(a60+a61);
  a62=(a48*a62);
  a63=(a52*a43);
  a64=(a54*a33);
  a64=(a63+a64);
  a64=(a64+a1);
  a62=(a62+a64);
  a59=(a59+a62);
  a57=(a57+a59);
  if (res[0]!=0) res[0][25]=a57;
  a57=(a5*a13);
  a57=(a3*a57);
  a57=(a57-a38);
  a38=(a57*a36);
  a34=(a34+a56);
  a34=(a3*a34);
  a34=(a32-a34);
  a56=(a34*a40);
  a59=(a10*a13);
  a59=(a3*a59);
  a51=(a51+a59);
  a59=(a51*a25);
  a56=(a56-a59);
  a59=(a56*a26);
  a38=(a38-a59);
  a59=(a38*a44);
  a62=(a57*a26);
  a64=(a56*a36);
  a62=(a62+a64);
  a64=(a62*a27);
  a59=(a59+a64);
  a59=(a31*a59);
  a64=(a31*a62);
  a65=(a51*a40);
  a66=(a34*a25);
  a67=(a65+a66);
  a67=(a48*a67);
  a68=(a52*a57);
  a69=(a54*a51);
  a69=(a68+a69);
  a69=(a69+a2);
  a67=(a67+a69);
  a64=(a64+a67);
  a59=(a59+a64);
  if (res[0]!=0) res[0][26]=a59;
  a59=cos(a29);
  a64=(a35*a59);
  a67=cos(a28);
  a69=(a39*a67);
  a28=sin(a28);
  a70=(a42*a28);
  a69=(a69-a70);
  a29=sin(a29);
  a70=(a69*a29);
  a64=(a64-a70);
  a70=sin(a30);
  a71=(a64*a70);
  a35=(a35*a29);
  a72=(a69*a59);
  a35=(a35+a72);
  a30=cos(a30);
  a72=(a35*a30);
  a71=(a71+a72);
  a71=(a31*a71);
  a72=(a31*a35);
  a73=8.6800000000000002e-02;
  a74=(a42*a67);
  a39=(a39*a28);
  a75=(a74+a39);
  a75=(a73*a75);
  a76=5.0999999999999997e-02;
  a42=(a76*a42);
  a53=(a53+a42);
  a53=(a53+a0);
  a75=(a75+a53);
  a72=(a72+a75);
  a71=(a71+a72);
  if (res[0]!=0) res[0][27]=a71;
  a71=(a43*a59);
  a72=(a47*a67);
  a75=(a33*a28);
  a72=(a72-a75);
  a75=(a72*a29);
  a71=(a71-a75);
  a75=(a71*a70);
  a43=(a43*a29);
  a53=(a72*a59);
  a43=(a43+a53);
  a53=(a43*a30);
  a75=(a75+a53);
  a75=(a31*a75);
  a53=(a31*a43);
  a0=(a33*a67);
  a47=(a47*a28);
  a42=(a0+a47);
  a42=(a73*a42);
  a33=(a76*a33);
  a63=(a63+a33);
  a63=(a63+a1);
  a42=(a42+a63);
  a53=(a53+a42);
  a75=(a75+a53);
  if (res[0]!=0) res[0][28]=a75;
  a75=(a57*a59);
  a53=(a34*a67);
  a42=(a51*a28);
  a53=(a53-a42);
  a42=(a53*a29);
  a75=(a75-a42);
  a42=(a75*a70);
  a57=(a57*a29);
  a63=(a53*a59);
  a57=(a57+a63);
  a63=(a57*a30);
  a42=(a42+a63);
  a42=(a31*a42);
  a63=(a31*a57);
  a1=(a51*a67);
  a34=(a34*a28);
  a33=(a1+a34);
  a33=(a73*a33);
  a51=(a76*a51);
  a68=(a68+a51);
  a68=(a68+a2);
  a33=(a33+a68);
  a63=(a63+a33);
  a42=(a42+a63);
  if (res[0]!=0) res[0][29]=a42;
  if (res[1]!=0) res[1][0]=a32;
  if (res[1]!=0) res[1][1]=a32;
  if (res[1]!=0) res[1][2]=a32;
  a42=(a3*a4);
  a42=(a21*a42);
  a63=casadi_sq(a20);
  a15=(a15+a63);
  a20=(a20/a15);
  a6=(a6+a6);
  a63=(a6*a4);
  a17=(a17+a17);
  a33=(a17*a9);
  a63=(a63-a33);
  a14=(a14+a14);
  a33=(a14*a12);
  a63=(a63+a33);
  a33=(a19+a19);
  a63=(a63/a33);
  a68=(a20*a63);
  a15=(a19/a15);
  a2=(a15*a8);
  a68=(a68-a2);
  a2=(a11*a68);
  a2=(a42+a2);
  a2=(a2/a19);
  a22=(a22/a19);
  a51=(a22*a63);
  a2=(a2-a51);
  if (res[1]!=0) res[1][3]=a2;
  a2=(a3*a9);
  a2=(a21*a2);
  a51=(a6*a9);
  a77=(a17*a4);
  a51=(a51+a77);
  a77=(a14*a8);
  a51=(a51-a77);
  a51=(a51/a33);
  a77=(a20*a51);
  a78=(a15*a12);
  a77=(a77-a78);
  a78=(a11*a77);
  a78=(a2+a78);
  a78=(a78/a19);
  a79=(a22*a51);
  a78=(a78-a79);
  if (res[1]!=0) res[1][4]=a78;
  a78=(a17*a8);
  a79=(a6*a12);
  a78=(a78-a79);
  a79=(a14*a4);
  a78=(a78+a79);
  a78=(a78/a33);
  a79=(a20*a78);
  a80=(a15*a9);
  a79=(a79-a80);
  a80=(a11*a79);
  a81=(a3*a12);
  a81=(a21*a81);
  a80=(a80-a81);
  a80=(a80/a19);
  a82=(a22*a78);
  a80=(a80-a82);
  if (res[1]!=0) res[1][5]=a80;
  a6=(a6*a8);
  a17=(a17*a12);
  a6=(a6+a17);
  a14=(a14*a9);
  a6=(a6+a14);
  a6=(a6/a33);
  a22=(a22*a6);
  a8=(a3*a8);
  a21=(a21*a8);
  a20=(a20*a6);
  a15=(a15*a4);
  a20=(a20+a15);
  a11=(a11*a20);
  a11=(a21+a11);
  a11=(a11/a19);
  a22=(a22-a11);
  if (res[1]!=0) res[1][6]=a22;
  a22=(a16*a68);
  a22=(a22-a2);
  a22=(a22/a19);
  a23=(a23/a19);
  a11=(a23*a63);
  a22=(a22-a11);
  if (res[1]!=0) res[1][7]=a22;
  a22=(a16*a77);
  a22=(a42+a22);
  a22=(a22/a19);
  a11=(a23*a51);
  a22=(a22-a11);
  if (res[1]!=0) res[1][8]=a22;
  a22=(a16*a79);
  a22=(a21+a22);
  a22=(a22/a19);
  a11=(a23*a78);
  a22=(a22-a11);
  if (res[1]!=0) res[1][9]=a22;
  a23=(a23*a6);
  a16=(a16*a20);
  a16=(a81+a16);
  a16=(a16/a19);
  a23=(a23-a16);
  if (res[1]!=0) res[1][10]=a23;
  a68=(a18*a68);
  a81=(a81+a68);
  a81=(a81/a19);
  a24=(a24/a19);
  a63=(a24*a63);
  a81=(a81-a63);
  if (res[1]!=0) res[1][11]=a81;
  a77=(a18*a77);
  a77=(a77-a21);
  a77=(a77/a19);
  a51=(a24*a51);
  a77=(a77-a51);
  if (res[1]!=0) res[1][12]=a77;
  a79=(a18*a79);
  a42=(a42+a79);
  a42=(a42/a19);
  a78=(a24*a78);
  a42=(a42-a78);
  if (res[1]!=0) res[1][13]=a42;
  a24=(a24*a6);
  a18=(a18*a20);
  a2=(a2+a18);
  a2=(a2/a19);
  a24=(a24-a2);
  if (res[1]!=0) res[1][14]=a24;
  if (res[1]!=0) res[1][15]=a32;
  if (res[1]!=0) res[1][16]=a32;
  if (res[1]!=0) res[1][17]=a32;
  if (res[1]!=0) res[1][18]=a32;
  if (res[1]!=0) res[1][19]=a32;
  if (res[1]!=0) res[1][20]=a32;
  if (res[1]!=0) res[1][21]=a32;
  if (res[1]!=0) res[1][22]=a32;
  if (res[1]!=0) res[1][23]=a32;
  if (res[1]!=0) res[1][24]=a32;
  if (res[1]!=0) res[1][25]=a32;
  if (res[1]!=0) res[1][26]=a32;
  if (res[1]!=0) res[1][27]=a32;
  if (res[1]!=0) res[1][28]=a32;
  if (res[1]!=0) res[1][29]=a32;
  if (res[1]!=0) res[1][30]=a32;
  if (res[1]!=0) res[1][31]=a32;
  if (res[1]!=0) res[1][32]=a32;
  if (res[1]!=0) res[1][33]=a32;
  a24=(a3*a13);
  a2=(a40*a24);
  a19=(a3*a10);
  a18=(a25*a19);
  a20=(a2-a18);
  a6=(a36*a20);
  a42=(a27*a6);
  a20=(a26*a20);
  a20=(a44*a20);
  a42=(a42-a20);
  a42=(a31*a42);
  a6=(a31*a6);
  a20=(a40*a19);
  a78=(a25*a24);
  a79=(a20+a78);
  a77=(a48*a79);
  a51=(a54*a19);
  a77=(a77+a51);
  a6=(a6+a77);
  a42=(a42+a6);
  if (res[1]!=0) res[1][34]=a42;
  a42=(a40*a7);
  a6=(a3*a5);
  a77=(a25*a6);
  a21=(a42-a77);
  a81=(a36*a21);
  a10=(a10+a10);
  a10=(a3*a10);
  a63=(a26*a10);
  a81=(a81-a63);
  a63=(a27*a81);
  a68=(a36*a10);
  a21=(a26*a21);
  a68=(a68+a21);
  a68=(a44*a68);
  a63=(a63-a68);
  a63=(a31*a63);
  a81=(a31*a81);
  a68=(a40*a6);
  a21=(a25*a7);
  a23=(a68+a21);
  a16=(a48*a23);
  a22=(a54*a6);
  a11=(a52*a10);
  a15=(a22-a11);
  a16=(a16+a15);
  a81=(a81+a16);
  a63=(a63+a81);
  if (res[1]!=0) res[1][35]=a63;
  a63=(a36*a23);
  a13=(a13+a13);
  a13=(a3*a13);
  a81=(a26*a13);
  a63=(a63-a81);
  a81=(a27*a63);
  a16=(a36*a13);
  a23=(a26*a23);
  a16=(a16+a23);
  a16=(a44*a16);
  a81=(a81-a16);
  a81=(a31*a81);
  a63=(a31*a63);
  a16=(a77-a42);
  a16=(a48*a16);
  a23=(a52*a13);
  a15=(a54*a7);
  a4=(a23+a15);
  a16=(a16-a4);
  a63=(a63+a16);
  a81=(a81+a63);
  if (res[1]!=0) res[1][36]=a81;
  a81=(a36*a79);
  a63=(a27*a81);
  a79=(a26*a79);
  a79=(a44*a79);
  a63=(a63-a79);
  a63=(a31*a63);
  a81=(a31*a81);
  a79=(a18-a2);
  a79=(a48*a79);
  a16=(a54*a24);
  a79=(a79-a16);
  a81=(a81+a79);
  a63=(a63+a81);
  if (res[1]!=0) res[1][37]=a63;
  a50=(a50+a49);
  a49=(a26*a50);
  a49=(a44*a49);
  a50=(a36*a50);
  a63=(a27*a50);
  a49=(a49-a63);
  a49=(a31*a49);
  a41=(a48*a41);
  a50=(a31*a50);
  a41=(a41-a50);
  a49=(a49+a41);
  if (res[1]!=0) res[1][38]=a49;
  a49=(a27*a37);
  a41=(a44*a46);
  a49=(a49-a41);
  a49=(a31*a49);
  a41=(a31*a37);
  a49=(a49+a41);
  if (res[1]!=0) res[1][39]=a49;
  a37=(a37*a27);
  a46=(a46*a44);
  a37=(a37-a46);
  a37=(a31*a37);
  if (res[1]!=0) res[1][40]=a37;
  if (res[1]!=0) res[1][41]=a32;
  a37=(a36*a19);
  a5=(a5+a5);
  a3=(a3*a5);
  a5=(a25*a3);
  a46=(a5-a42);
  a49=(a26*a46);
  a49=(a37-a49);
  a49=(a44*a49);
  a41=(a26*a19);
  a46=(a36*a46);
  a46=(a41+a46);
  a50=(a27*a46);
  a49=(a49+a50);
  a49=(a31*a49);
  a46=(a31*a46);
  a50=(a52*a19);
  a63=(a54*a3);
  a63=(a50-a63);
  a81=(a40*a3);
  a81=(a81+a21);
  a21=(a48*a81);
  a63=(a63-a21);
  a46=(a46+a63);
  a49=(a49+a46);
  if (res[1]!=0) res[1][42]=a49;
  a49=(a36*a6);
  a46=(a26*a2);
  a46=(a49-a46);
  a46=(a44*a46);
  a63=(a26*a6);
  a21=(a36*a2);
  a21=(a63+a21);
  a79=(a27*a21);
  a46=(a46+a79);
  a46=(a31*a46);
  a21=(a31*a21);
  a79=(a48*a78);
  a4=(a52*a6);
  a79=(a79+a4);
  a21=(a21+a79);
  a46=(a46+a21);
  if (res[1]!=0) res[1][43]=a46;
  a46=(a36*a7);
  a21=(a25*a13);
  a21=(a20+a21);
  a79=(a26*a21);
  a79=(a46-a79);
  a79=(a44*a79);
  a8=(a26*a7);
  a21=(a36*a21);
  a21=(a8+a21);
  a33=(a27*a21);
  a79=(a79+a33);
  a79=(a31*a79);
  a21=(a31*a21);
  a33=(a40*a13);
  a33=(a18-a33);
  a33=(a48*a33);
  a14=(a52*a7);
  a54=(a54*a13);
  a54=(a14-a54);
  a33=(a33+a54);
  a21=(a21+a33);
  a79=(a79+a21);
  if (res[1]!=0) res[1][44]=a79;
  a79=(a36*a24);
  a21=(a26*a68);
  a21=(a79+a21);
  a21=(a44*a21);
  a33=(a26*a24);
  a54=(a36*a68);
  a54=(a33-a54);
  a9=(a27*a54);
  a21=(a21+a9);
  a21=(a31*a21);
  a54=(a31*a54);
  a52=(a52*a24);
  a9=(a48*a77);
  a9=(a52-a9);
  a54=(a54+a9);
  a21=(a21+a54);
  if (res[1]!=0) res[1][45]=a21;
  a61=(a61+a60);
  a60=(a26*a61);
  a60=(a44*a60);
  a61=(a36*a61);
  a21=(a27*a61);
  a60=(a60-a21);
  a60=(a31*a60);
  a55=(a48*a55);
  a61=(a31*a61);
  a55=(a55-a61);
  a60=(a60+a55);
  if (res[1]!=0) res[1][46]=a60;
  a60=(a27*a45);
  a55=(a44*a58);
  a60=(a60-a55);
  a60=(a31*a60);
  a55=(a31*a45);
  a60=(a60+a55);
  if (res[1]!=0) res[1][47]=a60;
  a45=(a45*a27);
  a58=(a58*a44);
  a45=(a45-a58);
  a45=(a31*a45);
  if (res[1]!=0) res[1][48]=a45;
  if (res[1]!=0) res[1][49]=a32;
  a45=(a26*a81);
  a79=(a79+a45);
  a79=(a44*a79);
  a81=(a36*a81);
  a33=(a33-a81);
  a81=(a27*a33);
  a79=(a79+a81);
  a79=(a31*a79);
  a33=(a31*a33);
  a42=(a42-a5);
  a42=(a48*a42);
  a15=(a52+a15);
  a42=(a42+a15);
  a33=(a33+a42);
  a79=(a79+a33);
  if (res[1]!=0) res[1][50]=a79;
  a40=(a40*a10);
  a40=(a40+a78);
  a78=(a26*a40);
  a78=(a78-a46);
  a78=(a44*a78);
  a40=(a36*a40);
  a8=(a8+a40);
  a40=(a27*a8);
  a78=(a78-a40);
  a78=(a31*a78);
  a25=(a25*a10);
  a2=(a2-a25);
  a2=(a48*a2);
  a16=(a16-a14);
  a2=(a2+a16);
  a8=(a31*a8);
  a2=(a2-a8);
  a78=(a78+a2);
  if (res[1]!=0) res[1][51]=a78;
  a78=(a26*a18);
  a49=(a49+a78);
  a49=(a44*a49);
  a18=(a36*a18);
  a63=(a63-a18);
  a18=(a27*a63);
  a49=(a49+a18);
  a49=(a31*a49);
  a63=(a31*a63);
  a20=(a48*a20);
  a51=(a4+a51);
  a20=(a20+a51);
  a63=(a63+a20);
  a49=(a49+a63);
  if (res[1]!=0) res[1][52]=a49;
  a49=(a26*a77);
  a49=(a49-a37);
  a49=(a44*a49);
  a77=(a36*a77);
  a41=(a41+a77);
  a77=(a27*a41);
  a49=(a49-a77);
  a49=(a31*a49);
  a68=(a48*a68);
  a22=(a22-a50);
  a68=(a68+a22);
  a41=(a31*a41);
  a68=(a68-a41);
  a49=(a49+a68);
  if (res[1]!=0) res[1][53]=a49;
  a66=(a66+a65);
  a26=(a26*a66);
  a26=(a44*a26);
  a36=(a36*a66);
  a66=(a27*a36);
  a26=(a26-a66);
  a26=(a31*a26);
  a48=(a48*a56);
  a36=(a31*a36);
  a48=(a48-a36);
  a26=(a26+a48);
  if (res[1]!=0) res[1][54]=a26;
  a26=(a27*a38);
  a48=(a44*a62);
  a26=(a26-a48);
  a26=(a31*a26);
  a48=(a31*a38);
  a26=(a26+a48);
  if (res[1]!=0) res[1][55]=a26;
  a38=(a38*a27);
  a62=(a62*a44);
  a38=(a38-a62);
  a38=(a31*a38);
  if (res[1]!=0) res[1][56]=a38;
  if (res[1]!=0) res[1][57]=a32;
  a38=(a67*a24);
  a62=(a28*a19);
  a44=(a38-a62);
  a27=(a59*a44);
  a26=(a30*a27);
  a44=(a29*a44);
  a44=(a70*a44);
  a26=(a26-a44);
  a26=(a31*a26);
  a27=(a31*a27);
  a44=(a67*a19);
  a48=(a28*a24);
  a36=(a44+a48);
  a56=(a73*a36);
  a66=(a76*a19);
  a56=(a56+a66);
  a27=(a27+a56);
  a26=(a26+a27);
  if (res[1]!=0) res[1][58]=a26;
  a26=(a67*a7);
  a27=(a28*a6);
  a56=(a26-a27);
  a65=(a59*a56);
  a49=(a29*a10);
  a65=(a65-a49);
  a49=(a30*a65);
  a68=(a59*a10);
  a56=(a29*a56);
  a68=(a68+a56);
  a68=(a70*a68);
  a49=(a49-a68);
  a49=(a31*a49);
  a65=(a31*a65);
  a68=(a67*a6);
  a56=(a28*a7);
  a41=(a68+a56);
  a22=(a73*a41);
  a77=(a76*a6);
  a11=(a77-a11);
  a22=(a22+a11);
  a65=(a65+a22);
  a49=(a49+a65);
  if (res[1]!=0) res[1][59]=a49;
  a49=(a59*a41);
  a65=(a29*a13);
  a49=(a49-a65);
  a65=(a30*a49);
  a22=(a59*a13);
  a41=(a29*a41);
  a22=(a22+a41);
  a22=(a70*a22);
  a65=(a65-a22);
  a65=(a31*a65);
  a49=(a31*a49);
  a22=(a27-a26);
  a22=(a73*a22);
  a41=(a76*a7);
  a23=(a23+a41);
  a22=(a22-a23);
  a49=(a49+a22);
  a65=(a65+a49);
  if (res[1]!=0) res[1][60]=a65;
  a65=(a59*a36);
  a49=(a30*a65);
  a36=(a29*a36);
  a36=(a70*a36);
  a49=(a49-a36);
  a49=(a31*a49);
  a65=(a31*a65);
  a36=(a62-a38);
  a36=(a73*a36);
  a22=(a76*a24);
  a36=(a36-a22);
  a65=(a65+a36);
  a49=(a49+a65);
  if (res[1]!=0) res[1][61]=a49;
  a39=(a39+a74);
  a74=(a29*a39);
  a74=(a70*a74);
  a39=(a59*a39);
  a49=(a30*a39);
  a74=(a74-a49);
  a74=(a31*a74);
  a69=(a73*a69);
  a39=(a31*a39);
  a69=(a69-a39);
  a74=(a74+a69);
  if (res[1]!=0) res[1][62]=a74;
  a74=(a30*a64);
  a69=(a70*a35);
  a74=(a74-a69);
  a74=(a31*a74);
  a69=(a31*a64);
  a74=(a74+a69);
  if (res[1]!=0) res[1][63]=a74;
  a64=(a64*a30);
  a35=(a35*a70);
  a64=(a64-a35);
  a64=(a31*a64);
  if (res[1]!=0) res[1][64]=a64;
  if (res[1]!=0) res[1][65]=a32;
  a64=(a59*a19);
  a35=(a28*a3);
  a74=(a35-a26);
  a69=(a29*a74);
  a69=(a64-a69);
  a69=(a70*a69);
  a19=(a29*a19);
  a74=(a59*a74);
  a74=(a19+a74);
  a39=(a30*a74);
  a69=(a69+a39);
  a69=(a31*a69);
  a74=(a31*a74);
  a39=(a76*a3);
  a39=(a50-a39);
  a3=(a67*a3);
  a3=(a3+a56);
  a56=(a73*a3);
  a39=(a39-a56);
  a74=(a74+a39);
  a69=(a69+a74);
  if (res[1]!=0) res[1][66]=a69;
  a69=(a59*a6);
  a74=(a29*a38);
  a74=(a69-a74);
  a74=(a70*a74);
  a6=(a29*a6);
  a39=(a59*a38);
  a39=(a6+a39);
  a56=(a30*a39);
  a74=(a74+a56);
  a74=(a31*a74);
  a39=(a31*a39);
  a56=(a73*a48);
  a56=(a56+a4);
  a39=(a39+a56);
  a74=(a74+a39);
  if (res[1]!=0) res[1][67]=a74;
  a74=(a59*a7);
  a39=(a28*a13);
  a39=(a44+a39);
  a56=(a29*a39);
  a56=(a74-a56);
  a56=(a70*a56);
  a7=(a29*a7);
  a39=(a59*a39);
  a39=(a7+a39);
  a49=(a30*a39);
  a56=(a56+a49);
  a56=(a31*a56);
  a39=(a31*a39);
  a49=(a67*a13);
  a49=(a62-a49);
  a49=(a73*a49);
  a76=(a76*a13);
  a76=(a14-a76);
  a49=(a49+a76);
  a39=(a39+a49);
  a56=(a56+a39);
  if (res[1]!=0) res[1][68]=a56;
  a56=(a59*a24);
  a39=(a29*a68);
  a39=(a56+a39);
  a39=(a70*a39);
  a24=(a29*a24);
  a49=(a59*a68);
  a49=(a24-a49);
  a76=(a30*a49);
  a39=(a39+a76);
  a39=(a31*a39);
  a49=(a31*a49);
  a76=(a73*a27);
  a76=(a52-a76);
  a49=(a49+a76);
  a39=(a39+a49);
  if (res[1]!=0) res[1][69]=a39;
  a47=(a47+a0);
  a0=(a29*a47);
  a0=(a70*a0);
  a47=(a59*a47);
  a39=(a30*a47);
  a0=(a0-a39);
  a0=(a31*a0);
  a72=(a73*a72);
  a47=(a31*a47);
  a72=(a72-a47);
  a0=(a0+a72);
  if (res[1]!=0) res[1][70]=a0;
  a0=(a30*a71);
  a72=(a70*a43);
  a0=(a0-a72);
  a0=(a31*a0);
  a72=(a31*a71);
  a0=(a0+a72);
  if (res[1]!=0) res[1][71]=a0;
  a71=(a71*a30);
  a43=(a43*a70);
  a71=(a71-a43);
  a71=(a31*a71);
  if (res[1]!=0) res[1][72]=a71;
  if (res[1]!=0) res[1][73]=a32;
  a32=(a29*a3);
  a56=(a56+a32);
  a56=(a70*a56);
  a3=(a59*a3);
  a24=(a24-a3);
  a3=(a30*a24);
  a56=(a56+a3);
  a56=(a31*a56);
  a24=(a31*a24);
  a26=(a26-a35);
  a26=(a73*a26);
  a52=(a52+a41);
  a26=(a26+a52);
  a24=(a24+a26);
  a56=(a56+a24);
  if (res[1]!=0) res[1][74]=a56;
  a67=(a67*a10);
  a67=(a67+a48);
  a48=(a29*a67);
  a48=(a48-a74);
  a48=(a70*a48);
  a67=(a59*a67);
  a7=(a7+a67);
  a67=(a30*a7);
  a48=(a48-a67);
  a48=(a31*a48);
  a28=(a28*a10);
  a38=(a38-a28);
  a38=(a73*a38);
  a22=(a22-a14);
  a38=(a38+a22);
  a7=(a31*a7);
  a38=(a38-a7);
  a48=(a48+a38);
  if (res[1]!=0) res[1][75]=a48;
  a48=(a29*a62);
  a69=(a69+a48);
  a69=(a70*a69);
  a62=(a59*a62);
  a6=(a6-a62);
  a62=(a30*a6);
  a69=(a69+a62);
  a69=(a31*a69);
  a6=(a31*a6);
  a44=(a73*a44);
  a4=(a4+a66);
  a44=(a44+a4);
  a6=(a6+a44);
  a69=(a69+a6);
  if (res[1]!=0) res[1][76]=a69;
  a69=(a29*a27);
  a69=(a69-a64);
  a69=(a70*a69);
  a27=(a59*a27);
  a19=(a19+a27);
  a27=(a30*a19);
  a69=(a69-a27);
  a69=(a31*a69);
  a68=(a73*a68);
  a77=(a77-a50);
  a68=(a68+a77);
  a19=(a31*a19);
  a68=(a68-a19);
  a69=(a69+a68);
  if (res[1]!=0) res[1][77]=a69;
  a34=(a34+a1);
  a29=(a29*a34);
  a29=(a70*a29);
  a59=(a59*a34);
  a34=(a30*a59);
  a29=(a29-a34);
  a29=(a31*a29);
  a73=(a73*a53);
  a59=(a31*a59);
  a73=(a73-a59);
  a29=(a29+a73);
  if (res[1]!=0) res[1][78]=a29;
  a29=(a30*a75);
  a73=(a70*a57);
  a29=(a29-a73);
  a29=(a31*a29);
  a73=(a31*a75);
  a29=(a29+a73);
  if (res[1]!=0) res[1][79]=a29;
  a75=(a75*a30);
  a57=(a57*a70);
  a75=(a75-a57);
  a31=(a31*a75);
  if (res[1]!=0) res[1][80]=a31;
  return 0;
}

CASADI_SYMBOL_EXPORT int front_cost_y_e_fun_jac_ut_xt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int front_cost_y_e_fun_jac_ut_xt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int front_cost_y_e_fun_jac_ut_xt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void front_cost_y_e_fun_jac_ut_xt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int front_cost_y_e_fun_jac_ut_xt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void front_cost_y_e_fun_jac_ut_xt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void front_cost_y_e_fun_jac_ut_xt_incref(void) {
}

CASADI_SYMBOL_EXPORT void front_cost_y_e_fun_jac_ut_xt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int front_cost_y_e_fun_jac_ut_xt_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int front_cost_y_e_fun_jac_ut_xt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real front_cost_y_e_fun_jac_ut_xt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* front_cost_y_e_fun_jac_ut_xt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* front_cost_y_e_fun_jac_ut_xt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* front_cost_y_e_fun_jac_ut_xt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* front_cost_y_e_fun_jac_ut_xt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int front_cost_y_e_fun_jac_ut_xt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int front_cost_y_e_fun_jac_ut_xt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
