/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) back_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};
static const casadi_int casadi_s1[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[55] = {51, 1, 0, 51, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50};
static const casadi_int casadi_s4[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};

/* back_constr_h_fun:(i0[25],i1[18],i2[],i3[51])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a6, a7, a8, a9;
  a0=arg[3]? arg[3][2] : 0;
  a1=1.;
  a2=2.;
  a3=arg[0]? arg[0][5] : 0;
  a4=casadi_sq(a3);
  a5=arg[0]? arg[0][4] : 0;
  a6=casadi_sq(a5);
  a7=(a4+a6);
  a7=(a2*a7);
  a7=(a1-a7);
  a8=arg[0]? arg[0][8] : 0;
  a9=cos(a8);
  a10=arg[0]? arg[0][9] : 0;
  a11=cos(a10);
  a12=(a9*a11);
  a8=sin(a8);
  a10=sin(a10);
  a13=(a8*a10);
  a12=(a12-a13);
  a13=(a7*a12);
  a14=arg[0]? arg[0][3] : 0;
  a15=(a5*a14);
  a15=(a2*a15);
  a16=arg[0]? arg[0][6] : 0;
  a16=(a2*a16);
  a17=(a16*a3);
  a15=(a15-a17);
  a18=arg[0]? arg[0][7] : 0;
  a19=sin(a18);
  a20=(a19*a8);
  a21=(a20*a11);
  a22=(a19*a9);
  a23=(a22*a10);
  a21=(a21+a23);
  a23=(a15*a21);
  a13=(a13+a23);
  a23=(a16*a5);
  a24=(a3*a14);
  a24=(a2*a24);
  a24=(a23+a24);
  a18=cos(a18);
  a25=(a18*a8);
  a26=(a25*a11);
  a27=(a18*a9);
  a28=(a27*a10);
  a26=(a26+a28);
  a28=(a24*a26);
  a13=(a13-a28);
  a28=(a13*a12);
  a9=(a9*a10);
  a29=(a8*a11);
  a9=(a9+a29);
  a29=(a7*a9);
  a20=(a20*a10);
  a30=(a22*a11);
  a20=(a20-a30);
  a30=(a15*a20);
  a29=(a29+a30);
  a11=(a27*a11);
  a25=(a25*a10);
  a11=(a11-a25);
  a25=(a24*a11);
  a29=(a29+a25);
  a25=(a29*a9);
  a28=(a28+a25);
  a25=(a28*a7);
  a10=(a13*a21);
  a30=(a15*a18);
  a31=(a24*a19);
  a30=(a30+a31);
  a31=(a30*a18);
  a10=(a10+a31);
  a31=(a29*a20);
  a10=(a10+a31);
  a31=(a10*a15);
  a25=(a25+a31);
  a31=(a30*a19);
  a32=(a13*a26);
  a31=(a31-a32);
  a32=(a29*a11);
  a31=(a31+a32);
  a32=(a31*a24);
  a25=(a25+a32);
  a25=(a0*a25);
  a32=arg[0]? arg[0][13] : 0;
  a25=(a25*a32);
  a33=(a14*a5);
  a33=(a2*a33);
  a17=(a17+a33);
  a33=(a28*a17);
  a34=casadi_sq(a14);
  a4=(a4+a34);
  a4=(a2*a4);
  a4=(a1-a4);
  a35=(a10*a4);
  a33=(a33+a35);
  a35=(a3*a5);
  a35=(a2*a35);
  a16=(a16*a14);
  a35=(a35-a16);
  a36=(a31*a35);
  a33=(a33+a36);
  a33=(a0*a33);
  a36=arg[0]? arg[0][14] : 0;
  a33=(a33*a36);
  a25=(a25+a33);
  a14=(a14*a3);
  a14=(a2*a14);
  a14=(a14-a23);
  a28=(a28*a14);
  a5=(a5*a3);
  a5=(a2*a5);
  a16=(a16+a5);
  a10=(a10*a16);
  a28=(a28+a10);
  a6=(a6+a34);
  a2=(a2*a6);
  a1=(a1-a2);
  a31=(a31*a1);
  a28=(a28+a31);
  a28=(a0*a28);
  a31=arg[0]? arg[0][15] : 0;
  a28=(a28*a31);
  a25=(a25+a28);
  a28=-2.5000000000000000e-01;
  a2=(a28*a20);
  a6=-8.6800000000000002e-02;
  a34=(a6*a18);
  a10=-5.0999999999999997e-02;
  a34=(a34+a10);
  a22=(a28*a22);
  a22=(a34-a22);
  a2=(a2+a22);
  a5=(a19*a2);
  a3=(a28*a11);
  a27=(a28*a27);
  a6=(a6*a19);
  a27=(a27+a6);
  a3=(a3+a27);
  a23=(a18*a3);
  a5=(a5-a23);
  a23=(a30*a5);
  a33=(a21*a3);
  a37=(a26*a2);
  a33=(a33+a37);
  a37=(a13*a33);
  a23=(a23-a37);
  a37=(a11*a2);
  a38=(a20*a3);
  a37=(a37-a38);
  a38=(a29*a37);
  a23=(a23+a38);
  a38=(a23*a7);
  a39=(a12*a3);
  a40=(a28*a9);
  a8=(a28*a8);
  a41=-2.4070000000000000e-01;
  a8=(a8+a41);
  a40=(a40+a8);
  a42=(a26*a40);
  a39=(a39+a42);
  a42=(a13*a39);
  a43=(a19*a40);
  a44=(a30*a43);
  a42=(a42-a44);
  a44=(a9*a3);
  a45=(a11*a40);
  a44=(a44-a45);
  a45=(a29*a44);
  a42=(a42+a45);
  a45=(a42*a15);
  a38=(a38+a45);
  a45=(a21*a40);
  a46=(a12*a2);
  a45=(a45-a46);
  a46=(a13*a45);
  a47=(a18*a40);
  a48=(a30*a47);
  a46=(a46+a48);
  a48=(a20*a40);
  a49=(a9*a2);
  a48=(a48-a49);
  a49=(a29*a48);
  a46=(a46+a49);
  a49=(a46*a24);
  a38=(a38+a49);
  a38=(a0*a38);
  a49=arg[0]? arg[0][16] : 0;
  a38=(a38*a49);
  a25=(a25+a38);
  a38=(a23*a17);
  a50=(a42*a4);
  a38=(a38+a50);
  a50=(a46*a35);
  a38=(a38+a50);
  a38=(a0*a38);
  a50=arg[0]? arg[0][17] : 0;
  a38=(a38*a50);
  a25=(a25+a38);
  a23=(a23*a14);
  a42=(a42*a16);
  a23=(a23+a42);
  a46=(a46*a1);
  a23=(a23+a46);
  a23=(a0*a23);
  a46=arg[0]? arg[0][18] : 0;
  a23=(a23*a46);
  a25=(a25+a23);
  a23=(a10*a18);
  a42=(a18*a2);
  a38=(a19*a3);
  a42=(a42+a38);
  a23=(a23-a42);
  a38=(a23*a9);
  a51=(a13*a38);
  a52=(a41*a9);
  a53=(a10*a20);
  a53=(a52+a53);
  a54=(a9*a40);
  a55=(a20*a2);
  a54=(a54+a55);
  a55=(a11*a3);
  a54=(a54+a55);
  a53=(a53-a54);
  a53=(a53*a12);
  a55=(a41*a12);
  a10=(a10*a21);
  a10=(a55+a10);
  a3=(a26*a3);
  a40=(a12*a40);
  a2=(a21*a2);
  a40=(a40+a2);
  a3=(a3-a40);
  a10=(a10+a3);
  a10=(a10*a9);
  a53=(a53-a10);
  a10=(a30*a53);
  a51=(a51+a10);
  a23=(a23*a12);
  a10=(a29*a23);
  a51=(a51-a10);
  a51=(a0*a51);
  a10=arg[0]? arg[0][19] : 0;
  a51=(a51*a10);
  a25=(a25+a51);
  a51=(a18*a34);
  a40=(a19*a6);
  a51=(a51+a40);
  a51=(a51-a42);
  a40=(a20*a18);
  a2=(a11*a19);
  a40=(a40+a2);
  a2=(a51*a40);
  a56=(a20*a34);
  a52=(a52+a56);
  a56=(a11*a6);
  a52=(a52+a56);
  a52=(a52-a54);
  a2=(a2-a52);
  a56=(a13*a2);
  a57=(a21*a18);
  a58=(a26*a19);
  a57=(a57-a58);
  a52=(a52*a57);
  a34=(a21*a34);
  a55=(a55+a34);
  a6=(a26*a6);
  a55=(a55-a6);
  a55=(a55+a3);
  a6=(a55*a40);
  a52=(a52-a6);
  a6=(a30*a52);
  a56=(a56+a6);
  a51=(a51*a57);
  a55=(a55-a51);
  a51=(a29*a55);
  a56=(a56+a51);
  a56=(a0*a56);
  a51=arg[0]? arg[0][20] : 0;
  a56=(a56*a51);
  a25=(a25+a56);
  a56=(a18*a22);
  a6=(a19*a27);
  a56=(a56+a6);
  a56=(a56-a42);
  a42=(a56*a40);
  a6=(a9*a8);
  a34=(a20*a22);
  a6=(a6+a34);
  a34=(a11*a27);
  a6=(a6+a34);
  a6=(a6-a54);
  a42=(a42-a6);
  a13=(a13*a42);
  a6=(a6*a57);
  a8=(a12*a8);
  a22=(a21*a22);
  a8=(a8+a22);
  a27=(a26*a27);
  a8=(a8-a27);
  a8=(a8+a3);
  a40=(a8*a40);
  a6=(a6-a40);
  a30=(a30*a6);
  a13=(a13+a30);
  a56=(a56*a57);
  a8=(a8-a56);
  a29=(a29*a8);
  a13=(a13+a29);
  a13=(a0*a13);
  a29=arg[0]? arg[0][21] : 0;
  a13=(a13*a29);
  a25=(a25+a13);
  if (res[0]!=0) res[0][0]=a25;
  a25=(a17*a12);
  a13=(a4*a21);
  a25=(a25+a13);
  a13=(a35*a26);
  a25=(a25-a13);
  a13=(a25*a12);
  a56=(a17*a9);
  a57=(a4*a20);
  a56=(a56+a57);
  a57=(a35*a11);
  a56=(a56+a57);
  a57=(a56*a9);
  a13=(a13+a57);
  a57=(a13*a7);
  a30=(a25*a21);
  a40=(a4*a18);
  a3=(a35*a19);
  a40=(a40+a3);
  a3=(a40*a18);
  a30=(a30+a3);
  a3=(a56*a20);
  a30=(a30+a3);
  a3=(a30*a15);
  a57=(a57+a3);
  a3=(a40*a19);
  a27=(a25*a26);
  a3=(a3-a27);
  a27=(a56*a11);
  a3=(a3+a27);
  a27=(a3*a24);
  a57=(a57+a27);
  a57=(a0*a57);
  a57=(a57*a32);
  a27=(a13*a17);
  a22=(a30*a4);
  a27=(a27+a22);
  a22=(a3*a35);
  a27=(a27+a22);
  a27=(a0*a27);
  a27=(a27*a36);
  a57=(a57+a27);
  a13=(a13*a14);
  a30=(a30*a16);
  a13=(a13+a30);
  a3=(a3*a1);
  a13=(a13+a3);
  a13=(a0*a13);
  a13=(a13*a31);
  a57=(a57+a13);
  a13=(a40*a5);
  a3=(a25*a33);
  a13=(a13-a3);
  a3=(a56*a37);
  a13=(a13+a3);
  a3=(a13*a7);
  a30=(a25*a39);
  a27=(a40*a43);
  a30=(a30-a27);
  a27=(a56*a44);
  a30=(a30+a27);
  a27=(a30*a15);
  a3=(a3+a27);
  a27=(a25*a45);
  a22=(a40*a47);
  a27=(a27+a22);
  a22=(a56*a48);
  a27=(a27+a22);
  a22=(a27*a24);
  a3=(a3+a22);
  a3=(a0*a3);
  a3=(a3*a49);
  a57=(a57+a3);
  a3=(a13*a17);
  a22=(a30*a4);
  a3=(a3+a22);
  a22=(a27*a35);
  a3=(a3+a22);
  a3=(a0*a3);
  a3=(a3*a50);
  a57=(a57+a3);
  a13=(a13*a14);
  a30=(a30*a16);
  a13=(a13+a30);
  a27=(a27*a1);
  a13=(a13+a27);
  a13=(a0*a13);
  a13=(a13*a46);
  a57=(a57+a13);
  a13=(a25*a38);
  a27=(a40*a53);
  a13=(a13+a27);
  a27=(a56*a23);
  a13=(a13-a27);
  a13=(a0*a13);
  a13=(a13*a10);
  a57=(a57+a13);
  a13=(a25*a2);
  a27=(a40*a52);
  a13=(a13+a27);
  a27=(a56*a55);
  a13=(a13+a27);
  a13=(a0*a13);
  a13=(a13*a51);
  a57=(a57+a13);
  a25=(a25*a42);
  a40=(a40*a6);
  a25=(a25+a40);
  a56=(a56*a8);
  a25=(a25+a56);
  a25=(a0*a25);
  a25=(a25*a29);
  a57=(a57+a25);
  if (res[0]!=0) res[0][1]=a57;
  a57=(a14*a12);
  a25=(a16*a21);
  a57=(a57+a25);
  a25=(a1*a26);
  a57=(a57-a25);
  a12=(a57*a12);
  a25=(a14*a9);
  a56=(a16*a20);
  a25=(a25+a56);
  a56=(a1*a11);
  a25=(a25+a56);
  a9=(a25*a9);
  a12=(a12+a9);
  a9=(a12*a7);
  a21=(a57*a21);
  a56=(a16*a18);
  a40=(a1*a19);
  a56=(a56+a40);
  a18=(a56*a18);
  a21=(a21+a18);
  a20=(a25*a20);
  a21=(a21+a20);
  a20=(a21*a15);
  a9=(a9+a20);
  a19=(a56*a19);
  a26=(a57*a26);
  a19=(a19-a26);
  a11=(a25*a11);
  a19=(a19+a11);
  a11=(a19*a24);
  a9=(a9+a11);
  a9=(a0*a9);
  a9=(a9*a32);
  a11=(a12*a17);
  a26=(a21*a4);
  a11=(a11+a26);
  a26=(a19*a35);
  a11=(a11+a26);
  a11=(a0*a11);
  a11=(a11*a36);
  a9=(a9+a11);
  a12=(a12*a14);
  a21=(a21*a16);
  a12=(a12+a21);
  a19=(a19*a1);
  a12=(a12+a19);
  a12=(a0*a12);
  a12=(a12*a31);
  a9=(a9+a12);
  a5=(a56*a5);
  a33=(a57*a33);
  a5=(a5-a33);
  a37=(a25*a37);
  a5=(a5+a37);
  a37=(a5*a7);
  a39=(a57*a39);
  a43=(a56*a43);
  a39=(a39-a43);
  a44=(a25*a44);
  a39=(a39+a44);
  a44=(a39*a15);
  a37=(a37+a44);
  a45=(a57*a45);
  a47=(a56*a47);
  a45=(a45+a47);
  a48=(a25*a48);
  a45=(a45+a48);
  a48=(a45*a24);
  a37=(a37+a48);
  a37=(a0*a37);
  a37=(a37*a49);
  a9=(a9+a37);
  a37=(a5*a17);
  a48=(a39*a4);
  a37=(a37+a48);
  a48=(a45*a35);
  a37=(a37+a48);
  a37=(a0*a37);
  a37=(a37*a50);
  a9=(a9+a37);
  a5=(a5*a14);
  a39=(a39*a16);
  a5=(a5+a39);
  a45=(a45*a1);
  a5=(a5+a45);
  a5=(a0*a5);
  a5=(a5*a46);
  a9=(a9+a5);
  a38=(a57*a38);
  a53=(a56*a53);
  a38=(a38+a53);
  a23=(a25*a23);
  a38=(a38-a23);
  a38=(a0*a38);
  a38=(a38*a10);
  a9=(a9+a38);
  a2=(a57*a2);
  a52=(a56*a52);
  a2=(a2+a52);
  a55=(a25*a55);
  a2=(a2+a55);
  a2=(a0*a2);
  a2=(a2*a51);
  a9=(a9+a2);
  a57=(a57*a42);
  a56=(a56*a6);
  a57=(a57+a56);
  a25=(a25*a8);
  a57=(a57+a25);
  a0=(a0*a57);
  a0=(a0*a29);
  a9=(a9+a0);
  if (res[0]!=0) res[0][2]=a9;
  a9=arg[3]? arg[3][3] : 0;
  a0=arg[0]? arg[0][11] : 0;
  a29=cos(a0);
  a57=arg[0]? arg[0][12] : 0;
  a25=cos(a57);
  a8=(a29*a25);
  a0=sin(a0);
  a57=sin(a57);
  a56=(a0*a57);
  a8=(a8-a56);
  a56=(a7*a8);
  a6=arg[0]? arg[0][10] : 0;
  a42=sin(a6);
  a2=(a42*a0);
  a51=(a2*a25);
  a55=(a42*a29);
  a52=(a55*a57);
  a51=(a51+a52);
  a52=(a15*a51);
  a56=(a56+a52);
  a6=cos(a6);
  a52=(a6*a0);
  a38=(a52*a25);
  a10=(a6*a29);
  a23=(a10*a57);
  a38=(a38+a23);
  a23=(a24*a38);
  a56=(a56-a23);
  a23=(a56*a8);
  a29=(a29*a57);
  a53=(a0*a25);
  a29=(a29+a53);
  a53=(a7*a29);
  a2=(a2*a57);
  a5=(a55*a25);
  a2=(a2-a5);
  a5=(a15*a2);
  a53=(a53+a5);
  a25=(a10*a25);
  a52=(a52*a57);
  a25=(a25-a52);
  a52=(a24*a25);
  a53=(a53+a52);
  a52=(a53*a29);
  a23=(a23+a52);
  a52=(a23*a7);
  a57=(a56*a51);
  a5=(a15*a6);
  a45=(a24*a42);
  a5=(a5+a45);
  a45=(a5*a6);
  a57=(a57+a45);
  a45=(a53*a2);
  a57=(a57+a45);
  a45=(a57*a15);
  a52=(a52+a45);
  a45=(a5*a42);
  a39=(a56*a38);
  a45=(a45-a39);
  a39=(a53*a25);
  a45=(a45+a39);
  a39=(a45*a24);
  a52=(a52+a39);
  a52=(a9*a52);
  a52=(a52*a32);
  a39=(a23*a17);
  a37=(a57*a4);
  a39=(a39+a37);
  a37=(a45*a35);
  a39=(a39+a37);
  a39=(a9*a39);
  a39=(a39*a36);
  a52=(a52+a39);
  a23=(a23*a14);
  a57=(a57*a16);
  a23=(a23+a57);
  a45=(a45*a1);
  a23=(a23+a45);
  a23=(a9*a23);
  a23=(a23*a31);
  a52=(a52+a23);
  a23=(a28*a2);
  a45=8.6800000000000002e-02;
  a57=(a45*a6);
  a39=5.0999999999999997e-02;
  a57=(a57+a39);
  a55=(a28*a55);
  a55=(a57-a55);
  a23=(a23+a55);
  a37=(a42*a23);
  a48=(a28*a25);
  a10=(a28*a10);
  a45=(a45*a42);
  a10=(a10+a45);
  a48=(a48+a10);
  a47=(a6*a48);
  a37=(a37-a47);
  a47=(a5*a37);
  a44=(a51*a48);
  a43=(a38*a23);
  a44=(a44+a43);
  a43=(a56*a44);
  a47=(a47-a43);
  a43=(a25*a23);
  a33=(a2*a48);
  a43=(a43-a33);
  a33=(a53*a43);
  a47=(a47+a33);
  a33=(a47*a7);
  a12=(a8*a48);
  a19=(a28*a29);
  a28=(a28*a0);
  a28=(a28+a41);
  a19=(a19+a28);
  a0=(a38*a19);
  a12=(a12+a0);
  a0=(a56*a12);
  a21=(a42*a19);
  a11=(a5*a21);
  a0=(a0-a11);
  a11=(a29*a48);
  a26=(a25*a19);
  a11=(a11-a26);
  a26=(a53*a11);
  a0=(a0+a26);
  a26=(a0*a15);
  a33=(a33+a26);
  a26=(a51*a19);
  a20=(a8*a23);
  a26=(a26-a20);
  a20=(a56*a26);
  a18=(a6*a19);
  a40=(a5*a18);
  a20=(a20+a40);
  a40=(a2*a19);
  a13=(a29*a23);
  a40=(a40-a13);
  a13=(a53*a40);
  a20=(a20+a13);
  a13=(a20*a24);
  a33=(a33+a13);
  a33=(a9*a33);
  a33=(a33*a49);
  a52=(a52+a33);
  a33=(a47*a17);
  a13=(a0*a4);
  a33=(a33+a13);
  a13=(a20*a35);
  a33=(a33+a13);
  a33=(a9*a33);
  a33=(a33*a50);
  a52=(a52+a33);
  a47=(a47*a14);
  a0=(a0*a16);
  a47=(a47+a0);
  a20=(a20*a1);
  a47=(a47+a20);
  a47=(a9*a47);
  a47=(a47*a46);
  a52=(a52+a47);
  a47=(a39*a6);
  a20=(a6*a23);
  a0=(a42*a48);
  a20=(a20+a0);
  a47=(a47-a20);
  a0=(a47*a29);
  a33=(a56*a0);
  a13=(a41*a29);
  a27=(a39*a2);
  a27=(a13+a27);
  a30=(a29*a19);
  a3=(a2*a23);
  a30=(a30+a3);
  a3=(a25*a48);
  a30=(a30+a3);
  a27=(a27-a30);
  a27=(a27*a8);
  a41=(a41*a8);
  a39=(a39*a51);
  a39=(a41+a39);
  a48=(a38*a48);
  a19=(a8*a19);
  a23=(a51*a23);
  a19=(a19+a23);
  a48=(a48-a19);
  a39=(a39+a48);
  a39=(a39*a29);
  a27=(a27-a39);
  a39=(a5*a27);
  a33=(a33+a39);
  a47=(a47*a8);
  a39=(a53*a47);
  a33=(a33-a39);
  a33=(a9*a33);
  a39=arg[0]? arg[0][22] : 0;
  a33=(a33*a39);
  a52=(a52+a33);
  a33=(a6*a57);
  a19=(a42*a45);
  a33=(a33+a19);
  a33=(a33-a20);
  a19=(a2*a6);
  a23=(a25*a42);
  a19=(a19+a23);
  a23=(a33*a19);
  a3=(a2*a57);
  a13=(a13+a3);
  a3=(a25*a45);
  a13=(a13+a3);
  a13=(a13-a30);
  a23=(a23-a13);
  a3=(a56*a23);
  a22=(a51*a6);
  a54=(a38*a42);
  a22=(a22-a54);
  a13=(a13*a22);
  a57=(a51*a57);
  a41=(a41+a57);
  a45=(a38*a45);
  a41=(a41-a45);
  a41=(a41+a48);
  a45=(a41*a19);
  a13=(a13-a45);
  a45=(a5*a13);
  a3=(a3+a45);
  a33=(a33*a22);
  a41=(a41-a33);
  a33=(a53*a41);
  a3=(a3+a33);
  a3=(a9*a3);
  a33=arg[0]? arg[0][23] : 0;
  a3=(a3*a33);
  a52=(a52+a3);
  a3=(a6*a55);
  a45=(a42*a10);
  a3=(a3+a45);
  a3=(a3-a20);
  a20=(a3*a19);
  a45=(a29*a28);
  a57=(a2*a55);
  a45=(a45+a57);
  a57=(a25*a10);
  a45=(a45+a57);
  a45=(a45-a30);
  a20=(a20-a45);
  a56=(a56*a20);
  a45=(a45*a22);
  a28=(a8*a28);
  a55=(a51*a55);
  a28=(a28+a55);
  a10=(a38*a10);
  a28=(a28-a10);
  a28=(a28+a48);
  a19=(a28*a19);
  a45=(a45-a19);
  a5=(a5*a45);
  a56=(a56+a5);
  a3=(a3*a22);
  a28=(a28-a3);
  a53=(a53*a28);
  a56=(a56+a53);
  a56=(a9*a56);
  a53=arg[0]? arg[0][24] : 0;
  a56=(a56*a53);
  a52=(a52+a56);
  if (res[0]!=0) res[0][3]=a52;
  a52=(a17*a8);
  a56=(a4*a51);
  a52=(a52+a56);
  a56=(a35*a38);
  a52=(a52-a56);
  a56=(a52*a8);
  a3=(a17*a29);
  a22=(a4*a2);
  a3=(a3+a22);
  a22=(a35*a25);
  a3=(a3+a22);
  a22=(a3*a29);
  a56=(a56+a22);
  a22=(a56*a7);
  a5=(a52*a51);
  a19=(a4*a6);
  a48=(a35*a42);
  a19=(a19+a48);
  a48=(a19*a6);
  a5=(a5+a48);
  a48=(a3*a2);
  a5=(a5+a48);
  a48=(a5*a15);
  a22=(a22+a48);
  a48=(a19*a42);
  a10=(a52*a38);
  a48=(a48-a10);
  a10=(a3*a25);
  a48=(a48+a10);
  a10=(a48*a24);
  a22=(a22+a10);
  a22=(a9*a22);
  a22=(a22*a32);
  a10=(a56*a17);
  a55=(a5*a4);
  a10=(a10+a55);
  a55=(a48*a35);
  a10=(a10+a55);
  a10=(a9*a10);
  a10=(a10*a36);
  a22=(a22+a10);
  a56=(a56*a14);
  a5=(a5*a16);
  a56=(a56+a5);
  a48=(a48*a1);
  a56=(a56+a48);
  a56=(a9*a56);
  a56=(a56*a31);
  a22=(a22+a56);
  a56=(a19*a37);
  a48=(a52*a44);
  a56=(a56-a48);
  a48=(a3*a43);
  a56=(a56+a48);
  a48=(a56*a7);
  a5=(a52*a12);
  a10=(a19*a21);
  a5=(a5-a10);
  a10=(a3*a11);
  a5=(a5+a10);
  a10=(a5*a15);
  a48=(a48+a10);
  a10=(a52*a26);
  a55=(a19*a18);
  a10=(a10+a55);
  a55=(a3*a40);
  a10=(a10+a55);
  a55=(a10*a24);
  a48=(a48+a55);
  a48=(a9*a48);
  a48=(a48*a49);
  a22=(a22+a48);
  a48=(a56*a17);
  a55=(a5*a4);
  a48=(a48+a55);
  a55=(a10*a35);
  a48=(a48+a55);
  a48=(a9*a48);
  a48=(a48*a50);
  a22=(a22+a48);
  a56=(a56*a14);
  a5=(a5*a16);
  a56=(a56+a5);
  a10=(a10*a1);
  a56=(a56+a10);
  a56=(a9*a56);
  a56=(a56*a46);
  a22=(a22+a56);
  a56=(a52*a0);
  a10=(a19*a27);
  a56=(a56+a10);
  a10=(a3*a47);
  a56=(a56-a10);
  a56=(a9*a56);
  a56=(a56*a39);
  a22=(a22+a56);
  a56=(a52*a23);
  a10=(a19*a13);
  a56=(a56+a10);
  a10=(a3*a41);
  a56=(a56+a10);
  a56=(a9*a56);
  a56=(a56*a33);
  a22=(a22+a56);
  a52=(a52*a20);
  a19=(a19*a45);
  a52=(a52+a19);
  a3=(a3*a28);
  a52=(a52+a3);
  a52=(a9*a52);
  a52=(a52*a53);
  a22=(a22+a52);
  if (res[0]!=0) res[0][4]=a22;
  a22=(a14*a8);
  a52=(a16*a51);
  a22=(a22+a52);
  a52=(a1*a38);
  a22=(a22-a52);
  a8=(a22*a8);
  a52=(a14*a29);
  a3=(a16*a2);
  a52=(a52+a3);
  a3=(a1*a25);
  a52=(a52+a3);
  a29=(a52*a29);
  a8=(a8+a29);
  a29=(a8*a7);
  a51=(a22*a51);
  a3=(a16*a6);
  a19=(a1*a42);
  a3=(a3+a19);
  a6=(a3*a6);
  a51=(a51+a6);
  a2=(a52*a2);
  a51=(a51+a2);
  a2=(a51*a15);
  a29=(a29+a2);
  a42=(a3*a42);
  a38=(a22*a38);
  a42=(a42-a38);
  a25=(a52*a25);
  a42=(a42+a25);
  a25=(a42*a24);
  a29=(a29+a25);
  a29=(a9*a29);
  a29=(a29*a32);
  a32=(a8*a17);
  a25=(a51*a4);
  a32=(a32+a25);
  a25=(a42*a35);
  a32=(a32+a25);
  a32=(a9*a32);
  a32=(a32*a36);
  a29=(a29+a32);
  a8=(a8*a14);
  a51=(a51*a16);
  a8=(a8+a51);
  a42=(a42*a1);
  a8=(a8+a42);
  a8=(a9*a8);
  a8=(a8*a31);
  a29=(a29+a8);
  a37=(a3*a37);
  a44=(a22*a44);
  a37=(a37-a44);
  a43=(a52*a43);
  a37=(a37+a43);
  a7=(a37*a7);
  a12=(a22*a12);
  a21=(a3*a21);
  a12=(a12-a21);
  a11=(a52*a11);
  a12=(a12+a11);
  a15=(a12*a15);
  a7=(a7+a15);
  a26=(a22*a26);
  a18=(a3*a18);
  a26=(a26+a18);
  a40=(a52*a40);
  a26=(a26+a40);
  a24=(a26*a24);
  a7=(a7+a24);
  a7=(a9*a7);
  a7=(a7*a49);
  a29=(a29+a7);
  a17=(a37*a17);
  a4=(a12*a4);
  a17=(a17+a4);
  a35=(a26*a35);
  a17=(a17+a35);
  a17=(a9*a17);
  a17=(a17*a50);
  a29=(a29+a17);
  a37=(a37*a14);
  a12=(a12*a16);
  a37=(a37+a12);
  a26=(a26*a1);
  a37=(a37+a26);
  a37=(a9*a37);
  a37=(a37*a46);
  a29=(a29+a37);
  a0=(a22*a0);
  a27=(a3*a27);
  a0=(a0+a27);
  a47=(a52*a47);
  a0=(a0-a47);
  a0=(a9*a0);
  a0=(a0*a39);
  a29=(a29+a0);
  a23=(a22*a23);
  a13=(a3*a13);
  a23=(a23+a13);
  a41=(a52*a41);
  a23=(a23+a41);
  a23=(a9*a23);
  a23=(a23*a33);
  a29=(a29+a23);
  a22=(a22*a20);
  a3=(a3*a45);
  a22=(a22+a3);
  a52=(a52*a28);
  a22=(a22+a52);
  a9=(a9*a22);
  a9=(a9*a53);
  a29=(a29+a9);
  if (res[0]!=0) res[0][5]=a29;
  return 0;
}

CASADI_SYMBOL_EXPORT int back_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int back_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int back_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void back_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int back_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void back_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void back_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void back_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int back_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int back_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real back_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* back_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* back_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* back_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* back_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int back_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int back_constr_h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
