/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) RL_cost_y_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[26] = {22, 1, 0, 22, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21};
static const casadi_int casadi_s1[19] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[57] = {53, 1, 0, 53, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52};
static const casadi_int casadi_s4[40] = {36, 1, 0, 36, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35};

/* RL_cost_y_fun:(i0[22],i1[15],i2[],i3[],i4[53])->(o0[36]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a1=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a1;
  a2=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a2;
  a3=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][3]=a3;
  a4=arg[0]? arg[0][8] : 0;
  if (res[0]!=0) res[0][4]=a4;
  a5=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][5]=a5;
  a6=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][6]=a6;
  a6=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][7]=a6;
  a6=arg[0]? arg[0][12] : 0;
  if (res[0]!=0) res[0][8]=a6;
  a6=arg[0]? arg[0][13] : 0;
  if (res[0]!=0) res[0][9]=a6;
  a6=arg[0]? arg[0][14] : 0;
  if (res[0]!=0) res[0][10]=a6;
  a6=arg[0]? arg[0][15] : 0;
  if (res[0]!=0) res[0][11]=a6;
  a6=arg[0]? arg[0][16] : 0;
  if (res[0]!=0) res[0][12]=a6;
  a6=arg[0]? arg[0][17] : 0;
  if (res[0]!=0) res[0][13]=a6;
  a6=arg[0]? arg[0][18] : 0;
  if (res[0]!=0) res[0][14]=a6;
  a6=arg[0]? arg[0][19] : 0;
  if (res[0]!=0) res[0][15]=a6;
  a6=arg[0]? arg[0][20] : 0;
  if (res[0]!=0) res[0][16]=a6;
  a6=arg[0]? arg[0][21] : 0;
  if (res[0]!=0) res[0][17]=a6;
  a6=-2.5000000000000000e-01;
  a7=1.;
  a8=2.;
  a9=arg[0]? arg[0][5] : 0;
  a10=casadi_sq(a9);
  a11=arg[0]? arg[0][4] : 0;
  a12=casadi_sq(a11);
  a10=(a10+a12);
  a10=(a8*a10);
  a10=(a7-a10);
  a12=cos(a4);
  a13=(a10*a12);
  a14=arg[0]? arg[0][6] : 0;
  a14=(a8*a14);
  a15=(a14*a11);
  a16=arg[0]? arg[0][3] : 0;
  a17=(a9*a16);
  a17=(a8*a17);
  a15=(a15+a17);
  a17=cos(a3);
  a18=(a15*a17);
  a19=(a11*a16);
  a19=(a8*a19);
  a20=(a14*a9);
  a19=(a19-a20);
  a3=sin(a3);
  a20=(a19*a3);
  a18=(a18-a20);
  a4=sin(a4);
  a20=(a18*a4);
  a13=(a13-a20);
  a20=sin(a5);
  a13=(a13*a20);
  a21=(a10*a4);
  a18=(a18*a12);
  a21=(a21+a18);
  a5=cos(a5);
  a18=(a21*a5);
  a13=(a13+a18);
  a13=(a6*a13);
  a21=(a6*a21);
  a18=8.3000000000000004e-02;
  a22=(a19*a17);
  a15=(a15*a3);
  a22=(a22+a15);
  a22=(a18*a22);
  a15=-2.3990000000000000e-01;
  a10=(a15*a10);
  a23=5.0999999999999997e-02;
  a19=(a23*a19);
  a10=(a10+a19);
  a10=(a10+a0);
  a22=(a22+a10);
  a21=(a21+a22);
  a13=(a13+a21);
  a21=arg[4]? arg[4][3] : 0;
  a13=(a13*a21);
  if (res[0]!=0) res[0][18]=a13;
  a13=(a14*a9);
  a22=(a16*a11);
  a22=(a8*a22);
  a13=(a13+a22);
  a22=(a13*a12);
  a10=(a9*a11);
  a10=(a8*a10);
  a0=(a14*a16);
  a10=(a10-a0);
  a0=(a10*a17);
  a19=casadi_sq(a9);
  a24=casadi_sq(a16);
  a19=(a19+a24);
  a19=(a8*a19);
  a19=(a7-a19);
  a24=(a19*a3);
  a0=(a0-a24);
  a24=(a0*a4);
  a22=(a22-a24);
  a22=(a22*a20);
  a24=(a13*a4);
  a0=(a0*a12);
  a24=(a24+a0);
  a0=(a24*a5);
  a22=(a22+a0);
  a22=(a6*a22);
  a24=(a6*a24);
  a0=(a19*a17);
  a10=(a10*a3);
  a0=(a0+a10);
  a0=(a18*a0);
  a13=(a15*a13);
  a19=(a23*a19);
  a13=(a13+a19);
  a13=(a13+a1);
  a0=(a0+a13);
  a24=(a24+a0);
  a22=(a22+a24);
  a22=(a22*a21);
  if (res[0]!=0) res[0][19]=a22;
  a22=(a16*a9);
  a22=(a8*a22);
  a24=(a14*a11);
  a22=(a22-a24);
  a24=(a22*a12);
  a0=casadi_sq(a11);
  a13=casadi_sq(a16);
  a0=(a0+a13);
  a0=(a8*a0);
  a7=(a7-a0);
  a0=(a7*a17);
  a14=(a14*a16);
  a11=(a11*a9);
  a8=(a8*a11);
  a14=(a14+a8);
  a8=(a14*a3);
  a0=(a0-a8);
  a8=(a0*a4);
  a24=(a24-a8);
  a24=(a24*a20);
  a4=(a22*a4);
  a0=(a0*a12);
  a4=(a4+a0);
  a5=(a4*a5);
  a24=(a24+a5);
  a24=(a6*a24);
  a6=(a6*a4);
  a17=(a14*a17);
  a7=(a7*a3);
  a17=(a17+a7);
  a18=(a18*a17);
  a15=(a15*a22);
  a23=(a23*a14);
  a15=(a15+a23);
  a15=(a15+a2);
  a18=(a18+a15);
  a6=(a6+a18);
  a24=(a24+a6);
  a24=(a24*a21);
  if (res[0]!=0) res[0][20]=a24;
  a24=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][21]=a24;
  a24=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][22]=a24;
  a24=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][23]=a24;
  a24=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][24]=a24;
  a24=arg[1]? arg[1][4] : 0;
  if (res[0]!=0) res[0][25]=a24;
  a24=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][26]=a24;
  a24=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][27]=a24;
  a24=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][28]=a24;
  a24=arg[1]? arg[1][8] : 0;
  if (res[0]!=0) res[0][29]=a24;
  a24=arg[1]? arg[1][9] : 0;
  if (res[0]!=0) res[0][30]=a24;
  a24=arg[1]? arg[1][10] : 0;
  if (res[0]!=0) res[0][31]=a24;
  a24=arg[1]? arg[1][11] : 0;
  if (res[0]!=0) res[0][32]=a24;
  a24=arg[1]? arg[1][12] : 0;
  if (res[0]!=0) res[0][33]=a24;
  a24=arg[1]? arg[1][13] : 0;
  if (res[0]!=0) res[0][34]=a24;
  a24=arg[1]? arg[1][14] : 0;
  if (res[0]!=0) res[0][35]=a24;
  return 0;
}

CASADI_SYMBOL_EXPORT int RL_cost_y_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int RL_cost_y_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int RL_cost_y_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RL_cost_y_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int RL_cost_y_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void RL_cost_y_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void RL_cost_y_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void RL_cost_y_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int RL_cost_y_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int RL_cost_y_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real RL_cost_y_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RL_cost_y_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* RL_cost_y_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RL_cost_y_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* RL_cost_y_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int RL_cost_y_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
