/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) FL_cost_y_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[26] = {22, 1, 0, 22, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21};
static const casadi_int casadi_s1[19] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[40] = {36, 1, 0, 36, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35};
static const casadi_int casadi_s4[57] = {53, 1, 0, 53, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52};
static const casadi_int casadi_s5[88] = {37, 37, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 14, 21, 27, 34, 41, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 18, 19, 20, 21, 22, 23, 24, 18, 19, 20, 21, 22, 23, 24, 18, 19, 20, 21, 22, 23, 24, 18, 19, 20, 22, 23, 24, 18, 19, 20, 21, 22, 23, 24, 18, 19, 20, 21, 22, 23, 24, 18, 19, 20, 21, 22, 23, 24};

/* FL_cost_y_hess:(i0[22],i1[15],i2[],i3[36],i4[],i5[53])->(o0[37x37,48nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a6, a7, a8, a9;
  a0=2.;
  a1=arg[0]? arg[0][7] : 0;
  a2=sin(a1);
  a3=8.3000000000000004e-02;
  a4=arg[5]? arg[5][1] : 0;
  a5=arg[3]? arg[3][20] : 0;
  a5=(a4*a5);
  a6=(a3*a5);
  a7=(a2*a6);
  a8=cos(a1);
  a9=arg[0]? arg[0][8] : 0;
  a10=cos(a9);
  a11=-2.5000000000000000e-01;
  a12=(a11*a5);
  a13=arg[0]? arg[0][9] : 0;
  a14=cos(a13);
  a15=(a11*a5);
  a16=(a14*a15);
  a12=(a12+a16);
  a16=(a10*a12);
  a17=sin(a9);
  a18=sin(a13);
  a19=(a18*a15);
  a20=(a17*a19);
  a16=(a16-a20);
  a20=(a8*a16);
  a7=(a7+a20);
  a7=(a0*a7);
  a20=(a0*a7);
  a21=5.0999999999999997e-02;
  a22=arg[3]? arg[3][19] : 0;
  a22=(a4*a22);
  a23=(a21*a22);
  a24=(a3*a22);
  a25=(a8*a24);
  a23=(a23+a25);
  a25=(a11*a22);
  a26=(a11*a22);
  a27=(a14*a26);
  a25=(a25+a27);
  a27=(a10*a25);
  a28=(a18*a26);
  a29=(a17*a28);
  a27=(a27-a29);
  a29=(a2*a27);
  a23=(a23-a29);
  a23=(a0*a23);
  a29=(a0*a23);
  a20=(a20+a29);
  a20=(-a20);
  if (res[0]!=0) res[0][0]=a20;
  a20=2.3990000000000000e-01;
  a22=(a20*a22);
  a29=(a17*a25);
  a22=(a22+a29);
  a29=(a10*a28);
  a22=(a22+a29);
  a29=(a0*a22);
  a30=arg[3]? arg[3][18] : 0;
  a4=(a4*a30);
  a30=(a21*a4);
  a3=(a3*a4);
  a31=(a8*a3);
  a30=(a30+a31);
  a31=(a11*a4);
  a11=(a11*a4);
  a14=(a14*a11);
  a31=(a31+a14);
  a14=(a10*a31);
  a18=(a18*a11);
  a32=(a17*a18);
  a14=(a14-a32);
  a32=(a2*a14);
  a30=(a30-a32);
  a32=(a0*a30);
  a33=(a29+a32);
  if (res[0]!=0) res[0][1]=a33;
  a33=(a20*a5);
  a34=(a17*a12);
  a33=(a33+a34);
  a34=(a10*a19);
  a33=(a33+a34);
  a34=(a0*a33);
  a35=(a2*a3);
  a36=(a8*a14);
  a35=(a35+a36);
  a36=(a0*a35);
  a37=(a34+a36);
  if (res[0]!=0) res[0][2]=a37;
  a21=(a21*a5);
  a5=(a8*a6);
  a21=(a21+a5);
  a5=(a2*a16);
  a21=(a21-a5);
  a5=(a2*a24);
  a37=(a8*a27);
  a5=(a5+a37);
  a37=(a21-a5);
  a37=(a0*a37);
  if (res[0]!=0) res[0][3]=a37;
  a37=cos(a1);
  a38=arg[0]? arg[0][3] : 0;
  a39=(a38+a38);
  a39=(a0*a39);
  a40=(a27*a39);
  a41=(a38+a38);
  a41=(a0*a41);
  a42=(a6*a41);
  a43=arg[0]? arg[0][6] : 0;
  a43=(a0*a43);
  a44=(a16*a43);
  a42=(a42+a44);
  a44=(a24*a43);
  a42=(a42+a44);
  a40=(a40-a42);
  a42=arg[0]? arg[0][5] : 0;
  a44=(a0*a42);
  a45=(a3*a44);
  a40=(a40+a45);
  a45=arg[0]? arg[0][4] : 0;
  a46=(a0*a45);
  a47=(a14*a46);
  a40=(a40-a47);
  a40=(a37*a40);
  a47=sin(a1);
  a48=(a6*a43);
  a49=(a16*a41);
  a48=(a48-a49);
  a49=(a24*a39);
  a48=(a48-a49);
  a49=(a27*a43);
  a48=(a48-a49);
  a49=(a3*a46);
  a48=(a48+a49);
  a49=(a14*a44);
  a48=(a48+a49);
  a48=(a47*a48);
  a40=(a40-a48);
  if (res[0]!=0) res[0][4]=a40;
  a40=cos(a9);
  a48=(a0*a42);
  a49=(a12*a48);
  a41=(a8*a41);
  a50=(a2*a43);
  a41=(a41+a50);
  a50=(a19*a41);
  a49=(a49+a50);
  a50=(a0*a45);
  a51=(a25*a50);
  a49=(a49+a51);
  a39=(a2*a39);
  a51=(a8*a43);
  a39=(a39-a51);
  a51=(a28*a39);
  a49=(a49-a51);
  a44=(a8*a44);
  a46=(a2*a46);
  a44=(a44-a46);
  a46=(a18*a44);
  a49=(a49-a46);
  a49=(a40*a49);
  a46=sin(a9);
  a51=(a19*a48);
  a52=(a12*a41);
  a51=(a51-a52);
  a52=(a25*a39);
  a51=(a51+a52);
  a52=(a28*a50);
  a51=(a51+a52);
  a52=(a31*a44);
  a51=(a51+a52);
  a51=(a46*a51);
  a49=(a49-a51);
  if (res[0]!=0) res[0][5]=a49;
  a49=cos(a13);
  a51=(a10*a48);
  a52=(a17*a41);
  a51=(a51+a52);
  a51=(a15*a51);
  a52=(a10*a50);
  a53=(a17*a39);
  a52=(a52-a53);
  a52=(a26*a52);
  a51=(a51+a52);
  a52=(a17*a44);
  a52=(a11*a52);
  a51=(a51-a52);
  a51=(a49*a51);
  a52=sin(a13);
  a48=(a17*a48);
  a41=(a10*a41);
  a48=(a48-a41);
  a48=(a15*a48);
  a50=(a17*a50);
  a39=(a10*a39);
  a50=(a50+a39);
  a50=(a26*a50);
  a48=(a48+a50);
  a44=(a10*a44);
  a44=(a11*a44);
  a48=(a48+a44);
  a48=(a52*a48);
  a51=(a51-a48);
  if (res[0]!=0) res[0][6]=a51;
  a29=(a29+a32);
  if (res[0]!=0) res[0][7]=a29;
  a7=(a0*a7);
  a20=(a20*a4);
  a4=(a17*a31);
  a20=(a20+a4);
  a4=(a10*a18);
  a20=(a20+a4);
  a20=(a0*a20);
  a4=(a0*a20);
  a7=(a7+a4);
  a7=(-a7);
  if (res[0]!=0) res[0][8]=a7;
  a7=(a0*a21);
  a4=(a0*a5);
  a29=(a7+a4);
  if (res[0]!=0) res[0][9]=a29;
  a29=(a35-a33);
  a29=(a0*a29);
  if (res[0]!=0) res[0][10]=a29;
  a29=(a0*a42);
  a32=(a24*a29);
  a51=(a45+a45);
  a51=(a0*a51);
  a48=(a6*a51);
  a44=(a0*a42);
  a50=(a16*a44);
  a48=(a48+a50);
  a32=(a32-a48);
  a48=(a3*a43);
  a32=(a32+a48);
  a48=(a0*a38);
  a50=(a14*a48);
  a32=(a32-a50);
  a32=(a37*a32);
  a50=(a6*a44);
  a39=(a16*a51);
  a50=(a50-a39);
  a39=(a27*a29);
  a50=(a50+a39);
  a39=(a3*a48);
  a50=(a50+a39);
  a39=(a14*a43);
  a50=(a50+a39);
  a50=(a47*a50);
  a32=(a32-a50);
  if (res[0]!=0) res[0][11]=a32;
  a51=(a8*a51);
  a44=(a2*a44);
  a51=(a51+a44);
  a44=(a19*a51);
  a32=(a12*a43);
  a44=(a44-a32);
  a32=(a0*a38);
  a50=(a25*a32);
  a44=(a44+a50);
  a29=(a8*a29);
  a50=(a28*a29);
  a44=(a44-a50);
  a50=(a45+a45);
  a50=(a0*a50);
  a39=(a31*a50);
  a44=(a44-a39);
  a39=(a8*a43);
  a48=(a2*a48);
  a39=(a39-a48);
  a48=(a18*a39);
  a44=(a44-a48);
  a44=(a40*a44);
  a48=(a25*a29);
  a41=(a12*a51);
  a53=(a19*a43);
  a41=(a41+a53);
  a48=(a48-a41);
  a41=(a28*a32);
  a48=(a48+a41);
  a41=(a31*a39);
  a48=(a48+a41);
  a41=(a18*a50);
  a48=(a48-a41);
  a48=(a46*a48);
  a44=(a44-a48);
  if (res[0]!=0) res[0][12]=a44;
  a44=(a17*a51);
  a48=(a10*a43);
  a44=(a44-a48);
  a44=(a15*a44);
  a48=(a10*a32);
  a41=(a17*a29);
  a48=(a48-a41);
  a48=(a26*a48);
  a44=(a44+a48);
  a48=(a10*a50);
  a41=(a17*a39);
  a48=(a48+a41);
  a48=(a11*a48);
  a44=(a44-a48);
  a44=(a49*a44);
  a32=(a17*a32);
  a29=(a10*a29);
  a32=(a32+a29);
  a32=(a26*a32);
  a29=(a17*a43);
  a51=(a10*a51);
  a29=(a29+a51);
  a29=(a15*a29);
  a32=(a32-a29);
  a39=(a10*a39);
  a50=(a17*a50);
  a39=(a39-a50);
  a39=(a11*a39);
  a32=(a32+a39);
  a32=(a52*a32);
  a44=(a44-a32);
  if (res[0]!=0) res[0][13]=a44;
  a34=(a34+a36);
  if (res[0]!=0) res[0][14]=a34;
  a7=(a7+a4);
  if (res[0]!=0) res[0][15]=a7;
  a23=(a0*a23);
  a20=(a0*a20);
  a23=(a23+a20);
  a23=(-a23);
  if (res[0]!=0) res[0][16]=a23;
  a23=(a22-a30);
  a23=(a0*a23);
  if (res[0]!=0) res[0][17]=a23;
  a23=(a0*a45);
  a20=(a24*a23);
  a7=(a0*a45);
  a4=(a16*a7);
  a20=(a20-a4);
  a4=(a42+a42);
  a4=(a0*a4);
  a34=(a27*a4);
  a20=(a20+a34);
  a34=(a0*a38);
  a36=(a3*a34);
  a20=(a20+a36);
  a36=(a14*a43);
  a20=(a20+a36);
  a20=(a37*a20);
  a36=(a6*a7);
  a44=(a24*a4);
  a36=(a36-a44);
  a44=(a27*a23);
  a36=(a36+a44);
  a44=(a3*a43);
  a36=(a36-a44);
  a44=(a14*a34);
  a36=(a36+a44);
  a36=(a47*a36);
  a20=(a20-a36);
  if (res[0]!=0) res[0][18]=a20;
  a20=(a0*a38);
  a36=(a12*a20);
  a7=(a2*a7);
  a44=(a19*a7);
  a36=(a36+a44);
  a44=(a25*a43);
  a36=(a36+a44);
  a23=(a8*a23);
  a4=(a2*a4);
  a23=(a23+a4);
  a4=(a28*a23);
  a36=(a36-a4);
  a4=(a42+a42);
  a4=(a0*a4);
  a44=(a31*a4);
  a36=(a36-a44);
  a34=(a8*a34);
  a44=(a2*a43);
  a34=(a34+a44);
  a44=(a18*a34);
  a36=(a36-a44);
  a36=(a40*a36);
  a44=(a19*a20);
  a32=(a12*a7);
  a44=(a44-a32);
  a32=(a25*a23);
  a44=(a44+a32);
  a32=(a28*a43);
  a44=(a44+a32);
  a32=(a31*a34);
  a44=(a44+a32);
  a32=(a18*a4);
  a44=(a44-a32);
  a44=(a46*a44);
  a36=(a36-a44);
  if (res[0]!=0) res[0][19]=a36;
  a36=(a10*a20);
  a44=(a17*a7);
  a36=(a36+a44);
  a36=(a15*a36);
  a44=(a10*a43);
  a32=(a17*a23);
  a44=(a44-a32);
  a44=(a26*a44);
  a36=(a36+a44);
  a44=(a10*a4);
  a32=(a17*a34);
  a44=(a44+a32);
  a44=(a11*a44);
  a36=(a36-a44);
  a36=(a49*a36);
  a20=(a17*a20);
  a7=(a10*a7);
  a20=(a20-a7);
  a20=(a15*a20);
  a7=(a17*a43);
  a23=(a10*a23);
  a7=(a7+a23);
  a7=(a26*a7);
  a20=(a20+a7);
  a34=(a10*a34);
  a4=(a17*a4);
  a34=(a34-a4);
  a34=(a11*a34);
  a20=(a20+a34);
  a20=(a52*a20);
  a36=(a36-a20);
  if (res[0]!=0) res[0][20]=a36;
  a21=(a0*a21);
  a5=(a0*a5);
  a21=(a21-a5);
  if (res[0]!=0) res[0][21]=a21;
  a35=(a0*a35);
  a33=(a0*a33);
  a35=(a35-a33);
  if (res[0]!=0) res[0][22]=a35;
  a22=(a0*a22);
  a30=(a0*a30);
  a22=(a22-a30);
  if (res[0]!=0) res[0][23]=a22;
  a22=(a0*a45);
  a30=(a3*a22);
  a35=(a0*a38);
  a33=(a16*a35);
  a21=(a0*a38);
  a5=(a24*a21);
  a33=(a33+a5);
  a30=(a30-a33);
  a33=(a0*a42);
  a5=(a14*a33);
  a30=(a30+a5);
  a30=(a37*a30);
  a5=(a6*a35);
  a36=(a27*a21);
  a5=(a5-a36);
  a36=(a3*a33);
  a5=(a5-a36);
  a36=(a14*a22);
  a5=(a5+a36);
  a5=(a47*a5);
  a30=(a30-a5);
  if (res[0]!=0) res[0][24]=a30;
  a35=(a2*a35);
  a30=(a19*a35);
  a5=(a0*a45);
  a36=(a12*a5);
  a30=(a30-a36);
  a36=(a0*a42);
  a20=(a25*a36);
  a30=(a30+a20);
  a21=(a8*a21);
  a20=(a28*a21);
  a30=(a30+a20);
  a22=(a8*a22);
  a33=(a2*a33);
  a22=(a22+a33);
  a33=(a18*a22);
  a30=(a30-a33);
  a30=(a40*a30);
  a33=(a28*a36);
  a20=(a12*a35);
  a34=(a19*a5);
  a20=(a20+a34);
  a34=(a25*a21);
  a20=(a20+a34);
  a33=(a33-a20);
  a20=(a31*a22);
  a33=(a33+a20);
  a33=(a46*a33);
  a30=(a30-a33);
  if (res[0]!=0) res[0][25]=a30;
  a30=(a17*a35);
  a33=(a10*a5);
  a30=(a30-a33);
  a30=(a15*a30);
  a33=(a10*a36);
  a20=(a17*a21);
  a33=(a33+a20);
  a33=(a26*a33);
  a30=(a30+a33);
  a33=(a17*a22);
  a33=(a11*a33);
  a30=(a30-a33);
  a30=(a49*a30);
  a36=(a17*a36);
  a21=(a10*a21);
  a36=(a36-a21);
  a36=(a26*a36);
  a5=(a17*a5);
  a35=(a10*a35);
  a5=(a5+a35);
  a5=(a15*a5);
  a36=(a36-a5);
  a22=(a10*a22);
  a22=(a11*a22);
  a36=(a36+a22);
  a36=(a52*a36);
  a30=(a30-a36);
  if (res[0]!=0) res[0][26]=a30;
  a30=(a38+a38);
  a36=sin(a1);
  a22=(a24*a36);
  a5=cos(a1);
  a35=(a27*a5);
  a22=(a22+a35);
  a22=(a0*a22);
  a35=(a30*a22);
  a21=(a6*a36);
  a33=(a16*a5);
  a21=(a21+a33);
  a33=(a43*a21);
  a20=(a38+a38);
  a34=(a6*a5);
  a4=(a16*a36);
  a34=(a34-a4);
  a34=(a0*a34);
  a4=(a20*a34);
  a33=(a33+a4);
  a35=(a35-a33);
  a33=(a24*a5);
  a4=(a27*a36);
  a33=(a33-a4);
  a4=(a43*a33);
  a35=(a35-a4);
  a4=(a3*a36);
  a7=(a14*a5);
  a4=(a4+a7);
  a7=(a0*a4);
  a23=(a45*a7);
  a35=(a35-a23);
  a23=(a3*a5);
  a44=(a14*a36);
  a23=(a23-a44);
  a44=(a0*a23);
  a32=(a42*a44);
  a35=(a35+a32);
  if (res[0]!=0) res[0][27]=a35;
  a35=(a0*a33);
  a32=(a42*a35);
  a39=(a0*a21);
  a50=(a42*a39);
  a29=(a45+a45);
  a34=(a29*a34);
  a50=(a50+a34);
  a32=(a32-a50);
  a7=(a38*a7);
  a32=(a32-a7);
  a7=(a43*a23);
  a32=(a32+a7);
  if (res[0]!=0) res[0][28]=a32;
  a32=(a42+a42);
  a22=(a32*a22);
  a39=(a45*a39);
  a22=(a22-a39);
  a35=(a45*a35);
  a22=(a22+a35);
  a35=(a43*a4);
  a22=(a22+a35);
  a44=(a38*a44);
  a22=(a22+a44);
  if (res[0]!=0) res[0][29]=a22;
  a4=(a42*a4);
  a21=(a38*a21);
  a33=(a38*a33);
  a21=(a21+a33);
  a4=(a4-a21);
  a23=(a45*a23);
  a4=(a4+a23);
  a4=(a0*a4);
  if (res[0]!=0) res[0][30]=a4;
  a4=1.;
  a23=casadi_sq(a45);
  a21=casadi_sq(a38);
  a23=(a23+a21);
  a23=(a0*a23);
  a23=(a4-a23);
  a21=(a23*a6);
  a33=(a43*a38);
  a22=(a45*a42);
  a22=(a0*a22);
  a33=(a33+a22);
  a22=(a33*a16);
  a21=(a21-a22);
  a22=(a42*a45);
  a22=(a0*a22);
  a44=(a43*a38);
  a22=(a22-a44);
  a44=(a22*a24);
  a21=(a21+a44);
  a44=casadi_sq(a42);
  a35=casadi_sq(a38);
  a44=(a44+a35);
  a44=(a0*a44);
  a44=(a4-a44);
  a35=(a44*a27);
  a21=(a21-a35);
  a35=(a43*a45);
  a39=(a42*a38);
  a39=(a0*a39);
  a35=(a35+a39);
  a39=(a35*a3);
  a21=(a21+a39);
  a39=(a45*a38);
  a39=(a0*a39);
  a7=(a43*a42);
  a39=(a39-a7);
  a7=(a39*a14);
  a21=(a21-a7);
  a7=sin(a1);
  a21=(a21*a7);
  a6=(a33*a6);
  a16=(a23*a16);
  a6=(a6+a16);
  a24=(a44*a24);
  a6=(a6+a24);
  a27=(a22*a27);
  a6=(a6+a27);
  a3=(a39*a3);
  a6=(a6+a3);
  a14=(a35*a14);
  a6=(a6+a14);
  a1=cos(a1);
  a6=(a6*a1);
  a21=(a21+a6);
  a21=(-a21);
  if (res[0]!=0) res[0][31]=a21;
  a21=(a23*a36);
  a6=(a33*a5);
  a21=(a21+a6);
  a6=(a19*a21);
  a1=(a22*a36);
  a14=(a44*a5);
  a1=(a1+a14);
  a14=(a28*a1);
  a6=(a6+a14);
  a36=(a35*a36);
  a5=(a39*a5);
  a36=(a36+a5);
  a5=(a18*a36);
  a6=(a6+a5);
  a6=(a40*a6);
  a5=(a12*a21);
  a14=(a25*a1);
  a5=(a5+a14);
  a14=(a31*a36);
  a5=(a5+a14);
  a5=(a46*a5);
  a6=(a6+a5);
  if (res[0]!=0) res[0][32]=a6;
  a6=(a17*a21);
  a6=(a15*a6);
  a5=(a17*a1);
  a5=(a26*a5);
  a6=(a6+a5);
  a5=(a17*a36);
  a5=(a11*a5);
  a6=(a6+a5);
  a6=(a49*a6);
  a21=(a10*a21);
  a21=(a15*a21);
  a1=(a10*a1);
  a1=(a26*a1);
  a21=(a21+a1);
  a36=(a10*a36);
  a36=(a11*a36);
  a21=(a21+a36);
  a21=(a52*a21);
  a6=(a6+a21);
  if (res[0]!=0) res[0][33]=a6;
  a6=sin(a9);
  a21=(a12*a6);
  a36=cos(a9);
  a1=(a19*a36);
  a21=(a21+a1);
  a1=(a2*a21);
  a5=(a43*a1);
  a14=(a8*a21);
  a14=(a0*a14);
  a3=(a20*a14);
  a5=(a5+a3);
  a3=(a12*a36);
  a27=(a19*a6);
  a3=(a3-a27);
  a27=(a0*a3);
  a24=(a42*a27);
  a5=(a5+a24);
  a24=(a25*a6);
  a16=(a28*a36);
  a24=(a24+a16);
  a16=(a2*a24);
  a16=(a0*a16);
  a7=(a30*a16);
  a5=(a5-a7);
  a7=(a8*a24);
  a50=(a43*a7);
  a5=(a5+a50);
  a50=(a25*a36);
  a34=(a28*a6);
  a50=(a50-a34);
  a34=(a0*a50);
  a51=(a45*a34);
  a5=(a5+a51);
  a51=(a31*a6);
  a48=(a18*a36);
  a51=(a51+a48);
  a48=(a2*a51);
  a41=(a0*a48);
  a53=(a45*a41);
  a5=(a5+a53);
  a53=(a8*a51);
  a54=(a0*a53);
  a55=(a42*a54);
  a5=(a5-a55);
  if (res[0]!=0) res[0][34]=a5;
  a5=(a0*a1);
  a55=(a42*a5);
  a14=(a29*a14);
  a55=(a55+a14);
  a14=(a43*a3);
  a55=(a55-a14);
  a14=(a0*a7);
  a56=(a42*a14);
  a55=(a55-a56);
  a34=(a38*a34);
  a55=(a55+a34);
  a41=(a38*a41);
  a55=(a55+a41);
  a41=(a43*a53);
  a55=(a55-a41);
  a41=(a45+a45);
  a34=(a31*a36);
  a56=(a18*a6);
  a34=(a34-a56);
  a34=(a0*a34);
  a56=(a41*a34);
  a55=(a55-a56);
  if (res[0]!=0) res[0][35]=a55;
  a5=(a45*a5);
  a27=(a38*a27);
  a5=(a5+a27);
  a16=(a32*a16);
  a5=(a5-a16);
  a14=(a45*a14);
  a5=(a5-a14);
  a14=(a43*a50);
  a5=(a5+a14);
  a14=(a43*a48);
  a5=(a5-a14);
  a54=(a38*a54);
  a5=(a5-a54);
  a54=(a42+a42);
  a34=(a54*a34);
  a5=(a5-a34);
  if (res[0]!=0) res[0][36]=a5;
  a1=(a38*a1);
  a3=(a45*a3);
  a1=(a1-a3);
  a7=(a38*a7);
  a1=(a1+a7);
  a50=(a42*a50);
  a1=(a1+a50);
  a48=(a42*a48);
  a1=(a1-a48);
  a53=(a45*a53);
  a1=(a1-a53);
  a1=(a0*a1);
  if (res[0]!=0) res[0][37]=a1;
  a1=(a33*a21);
  a53=(a44*a24);
  a1=(a1+a53);
  a53=(a39*a51);
  a1=(a1+a53);
  a1=(a37*a1);
  a21=(a23*a21);
  a24=(a22*a24);
  a21=(a21+a24);
  a51=(a35*a51);
  a21=(a21+a51);
  a21=(a47*a21);
  a1=(a1+a21);
  if (res[0]!=0) res[0][38]=a1;
  a1=(a38*a42);
  a1=(a0*a1);
  a21=(a43*a45);
  a1=(a1-a21);
  a21=(a1*a12);
  a51=(a23*a8);
  a24=(a33*a2);
  a51=(a51-a24);
  a24=(a51*a19);
  a21=(a21-a24);
  a24=(a43*a42);
  a53=(a38*a45);
  a53=(a0*a53);
  a24=(a24+a53);
  a53=(a24*a25);
  a21=(a21+a53);
  a53=(a22*a8);
  a48=(a44*a2);
  a53=(a53-a48);
  a48=(a53*a28);
  a21=(a21-a48);
  a48=casadi_sq(a42);
  a50=casadi_sq(a45);
  a48=(a48+a50);
  a48=(a0*a48);
  a4=(a4-a48);
  a48=(a4*a31);
  a21=(a21+a48);
  a48=(a35*a8);
  a50=(a39*a2);
  a48=(a48-a50);
  a50=(a48*a18);
  a21=(a21-a50);
  a50=sin(a9);
  a21=(a21*a50);
  a12=(a51*a12);
  a19=(a1*a19);
  a12=(a12+a19);
  a25=(a53*a25);
  a12=(a12+a25);
  a28=(a24*a28);
  a12=(a12+a28);
  a31=(a48*a31);
  a12=(a12+a31);
  a18=(a4*a18);
  a12=(a12+a18);
  a9=cos(a9);
  a12=(a12*a9);
  a21=(a21+a12);
  a21=(-a21);
  if (res[0]!=0) res[0][39]=a21;
  a21=(a1*a6);
  a12=(a51*a36);
  a21=(a21+a12);
  a21=(a15*a21);
  a12=(a24*a6);
  a9=(a53*a36);
  a12=(a12+a9);
  a12=(a26*a12);
  a21=(a21+a12);
  a12=(a4*a6);
  a9=(a48*a36);
  a12=(a12+a9);
  a12=(a11*a12);
  a21=(a21+a12);
  a49=(a49*a21);
  a21=(a1*a36);
  a12=(a51*a6);
  a21=(a21-a12);
  a21=(a15*a21);
  a12=(a24*a36);
  a9=(a53*a6);
  a12=(a12-a9);
  a12=(a26*a12);
  a21=(a21+a12);
  a36=(a4*a36);
  a6=(a48*a6);
  a36=(a36-a6);
  a36=(a11*a36);
  a21=(a21+a36);
  a52=(a52*a21);
  a49=(a49+a52);
  a49=(-a49);
  if (res[0]!=0) res[0][40]=a49;
  a49=sin(a13);
  a52=(a15*a49);
  a21=(a10*a52);
  a36=cos(a13);
  a6=(a15*a36);
  a12=(a17*a6);
  a21=(a21+a12);
  a12=(a2*a21);
  a9=(a43*a12);
  a18=(a8*a21);
  a18=(a0*a18);
  a20=(a20*a18);
  a9=(a9+a20);
  a20=(a10*a6);
  a31=(a17*a52);
  a20=(a20-a31);
  a31=(a0*a20);
  a28=(a42*a31);
  a9=(a9+a28);
  a28=(a26*a49);
  a25=(a10*a28);
  a19=(a26*a36);
  a50=(a17*a19);
  a25=(a25+a50);
  a50=(a2*a25);
  a50=(a0*a50);
  a30=(a30*a50);
  a9=(a9-a30);
  a30=(a8*a25);
  a7=(a43*a30);
  a9=(a9+a7);
  a7=(a10*a19);
  a3=(a17*a28);
  a7=(a7-a3);
  a3=(a0*a7);
  a5=(a45*a3);
  a9=(a9+a5);
  a49=(a11*a49);
  a5=(a10*a49);
  a36=(a11*a36);
  a34=(a17*a36);
  a5=(a5+a34);
  a2=(a2*a5);
  a34=(a0*a2);
  a14=(a45*a34);
  a9=(a9+a14);
  a8=(a8*a5);
  a14=(a0*a8);
  a16=(a42*a14);
  a9=(a9-a16);
  if (res[0]!=0) res[0][41]=a9;
  a9=(a0*a12);
  a16=(a42*a9);
  a29=(a29*a18);
  a16=(a16+a29);
  a29=(a43*a20);
  a16=(a16-a29);
  a29=(a0*a30);
  a18=(a42*a29);
  a16=(a16-a18);
  a3=(a38*a3);
  a16=(a16+a3);
  a34=(a38*a34);
  a16=(a16+a34);
  a34=(a43*a8);
  a16=(a16-a34);
  a34=(a10*a36);
  a3=(a17*a49);
  a34=(a34-a3);
  a34=(a0*a34);
  a41=(a41*a34);
  a16=(a16-a41);
  if (res[0]!=0) res[0][42]=a16;
  a9=(a45*a9);
  a31=(a38*a31);
  a9=(a9+a31);
  a32=(a32*a50);
  a9=(a9-a32);
  a29=(a45*a29);
  a9=(a9-a29);
  a29=(a43*a7);
  a9=(a9+a29);
  a43=(a43*a2);
  a9=(a9-a43);
  a14=(a38*a14);
  a9=(a9-a14);
  a54=(a54*a34);
  a9=(a9-a54);
  if (res[0]!=0) res[0][43]=a9;
  a12=(a38*a12);
  a20=(a45*a20);
  a12=(a12-a20);
  a38=(a38*a30);
  a12=(a12+a38);
  a7=(a42*a7);
  a12=(a12+a7);
  a42=(a42*a2);
  a12=(a12-a42);
  a45=(a45*a8);
  a12=(a12-a45);
  a0=(a0*a12);
  if (res[0]!=0) res[0][44]=a0;
  a33=(a33*a21);
  a44=(a44*a25);
  a33=(a33+a44);
  a39=(a39*a5);
  a33=(a33+a39);
  a37=(a37*a33);
  a23=(a23*a21);
  a22=(a22*a25);
  a23=(a23+a22);
  a35=(a35*a5);
  a23=(a23+a35);
  a47=(a47*a23);
  a37=(a37+a47);
  if (res[0]!=0) res[0][45]=a37;
  a37=(a1*a52);
  a47=(a51*a6);
  a37=(a37+a47);
  a47=(a24*a28);
  a37=(a37+a47);
  a47=(a53*a19);
  a37=(a37+a47);
  a47=(a4*a49);
  a37=(a37+a47);
  a47=(a48*a36);
  a37=(a37+a47);
  a40=(a40*a37);
  a6=(a1*a6);
  a52=(a51*a52);
  a6=(a6-a52);
  a28=(a53*a28);
  a6=(a6-a28);
  a19=(a24*a19);
  a6=(a6+a19);
  a49=(a48*a49);
  a6=(a6-a49);
  a36=(a4*a36);
  a6=(a6+a36);
  a46=(a46*a6);
  a40=(a40+a46);
  a40=(-a40);
  if (res[0]!=0) res[0][46]=a40;
  a40=(a1*a10);
  a46=(a51*a17);
  a40=(a40-a46);
  a40=(a40*a15);
  a46=(a24*a10);
  a6=(a53*a17);
  a46=(a46-a6);
  a46=(a46*a26);
  a40=(a40+a46);
  a46=(a4*a10);
  a6=(a48*a17);
  a46=(a46-a6);
  a46=(a46*a11);
  a40=(a40+a46);
  a46=sin(a13);
  a40=(a40*a46);
  a1=(a1*a17);
  a51=(a51*a10);
  a1=(a1+a51);
  a1=(a1*a15);
  a24=(a24*a17);
  a53=(a53*a10);
  a24=(a24+a53);
  a24=(a24*a26);
  a1=(a1+a24);
  a4=(a4*a17);
  a48=(a48*a10);
  a4=(a4+a48);
  a4=(a4*a11);
  a1=(a1+a4);
  a13=cos(a13);
  a1=(a1*a13);
  a40=(a40+a1);
  a40=(-a40);
  if (res[0]!=0) res[0][47]=a40;
  return 0;
}

CASADI_SYMBOL_EXPORT int FL_cost_y_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int FL_cost_y_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int FL_cost_y_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FL_cost_y_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int FL_cost_y_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FL_cost_y_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void FL_cost_y_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void FL_cost_y_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int FL_cost_y_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int FL_cost_y_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real FL_cost_y_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FL_cost_y_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FL_cost_y_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FL_cost_y_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s2;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FL_cost_y_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int FL_cost_y_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
