/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) back_cost_y_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

static const casadi_int casadi_s0[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};
static const casadi_int casadi_s1[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[55] = {51, 1, 0, 51, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50};
static const casadi_int casadi_s4[78] = {74, 1, 0, 74, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73};

/* back_cost_y_fun:(i0[25],i1[18],i2[],i3[],i4[51])->(o0[74]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a1=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][1]=a1;
  a2=arg[0]? arg[0][2] : 0;
  if (res[0]!=0) res[0][2]=a2;
  a3=2.;
  a4=arg[4]? arg[4][37] : 0;
  a5=arg[0]? arg[0][3] : 0;
  a6=(a4*a5);
  a7=arg[0]? arg[0][6] : 0;
  a8=arg[4]? arg[4][34] : 0;
  a9=(a7*a8);
  a6=(a6-a9);
  a9=arg[4]? arg[4][36] : 0;
  a10=arg[0]? arg[0][4] : 0;
  a11=(a9*a10);
  a12=arg[4]? arg[4][35] : 0;
  a13=arg[0]? arg[0][5] : 0;
  a14=(a12*a13);
  a11=(a11-a14);
  a6=(a6+a11);
  a11=(a3*a6);
  a14=2.2204460492503131e-16;
  a6=(a6+a14);
  a6=casadi_sq(a6);
  a15=(a4*a10);
  a16=(a7*a12);
  a15=(a15-a16);
  a16=(a8*a13);
  a17=(a9*a5);
  a16=(a16-a17);
  a15=(a15+a16);
  a16=(a15+a14);
  a16=casadi_sq(a16);
  a6=(a6+a16);
  a16=(a4*a13);
  a17=(a7*a9);
  a16=(a16-a17);
  a17=(a12*a5);
  a18=(a8*a10);
  a17=(a17-a18);
  a16=(a16+a17);
  a14=(a16+a14);
  a14=casadi_sq(a14);
  a6=(a6+a14);
  a6=sqrt(a6);
  a4=(a4*a7);
  a8=(a8*a5);
  a12=(a12*a10);
  a8=(a8+a12);
  a9=(a9*a13);
  a8=(a8+a9);
  a4=(a4+a8);
  a4=atan2(a6,a4);
  a11=(a11*a4);
  a11=(a11/a6);
  if (res[0]!=0) res[0][3]=a11;
  a15=(a3*a15);
  a15=(a15*a4);
  a15=(a15/a6);
  if (res[0]!=0) res[0][4]=a15;
  a16=(a3*a16);
  a16=(a16*a4);
  a16=(a16/a6);
  if (res[0]!=0) res[0][5]=a16;
  a16=arg[0]? arg[0][7] : 0;
  if (res[0]!=0) res[0][6]=a16;
  a6=arg[0]? arg[0][8] : 0;
  if (res[0]!=0) res[0][7]=a6;
  a4=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][8]=a4;
  a15=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][9]=a15;
  a11=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][10]=a11;
  a8=arg[0]? arg[0][12] : 0;
  if (res[0]!=0) res[0][11]=a8;
  a9=arg[0]? arg[0][13] : 0;
  if (res[0]!=0) res[0][12]=a9;
  a12=arg[0]? arg[0][14] : 0;
  if (res[0]!=0) res[0][13]=a12;
  a14=arg[0]? arg[0][15] : 0;
  if (res[0]!=0) res[0][14]=a14;
  a17=arg[0]? arg[0][16] : 0;
  if (res[0]!=0) res[0][15]=a17;
  a18=arg[0]? arg[0][17] : 0;
  if (res[0]!=0) res[0][16]=a18;
  a19=arg[0]? arg[0][18] : 0;
  if (res[0]!=0) res[0][17]=a19;
  a20=arg[0]? arg[0][19] : 0;
  if (res[0]!=0) res[0][18]=a20;
  a20=arg[0]? arg[0][20] : 0;
  if (res[0]!=0) res[0][19]=a20;
  a20=arg[0]? arg[0][21] : 0;
  if (res[0]!=0) res[0][20]=a20;
  a20=arg[0]? arg[0][22] : 0;
  if (res[0]!=0) res[0][21]=a20;
  a20=arg[0]? arg[0][23] : 0;
  if (res[0]!=0) res[0][22]=a20;
  a20=arg[0]? arg[0][24] : 0;
  if (res[0]!=0) res[0][23]=a20;
  a20=2.5000000000000000e-01;
  a21=1.;
  a22=casadi_sq(a13);
  a23=casadi_sq(a10);
  a22=(a22+a23);
  a22=(a3*a22);
  a22=(a21-a22);
  a23=6.1232339957367660e-17;
  a24=cos(a16);
  a25=(a23*a24);
  a26=1.2246467991473532e-16;
  a16=sin(a16);
  a27=(a26*a16);
  a25=(a25+a27);
  a27=(a22*a25);
  a28=(a10*a5);
  a28=(a3*a28);
  a7=(a3*a7);
  a29=(a7*a13);
  a28=(a28-a29);
  a29=(a28*a16);
  a27=(a27-a29);
  a29=(a7*a10);
  a30=(a13*a5);
  a30=(a3*a30);
  a29=(a29+a30);
  a30=7.4987989133092880e-33;
  a31=(a30*a16);
  a31=(a31-a24);
  a32=(a29*a31);
  a27=(a27+a32);
  a32=cos(a6);
  a33=(a27*a32);
  a26=(a26*a24);
  a34=(a23*a16);
  a26=(a26-a34);
  a34=(a22*a26);
  a35=(a28*a24);
  a34=(a34-a35);
  a30=(a30*a24);
  a30=(a16+a30);
  a35=(a29*a30);
  a34=(a34+a35);
  a6=sin(a6);
  a35=(a23*a6);
  a36=(a34*a35);
  a33=(a33+a36);
  a36=-1.2246467991473532e-16;
  a37=(a36*a28);
  a37=(a37-a22);
  a38=-6.1232339957367660e-17;
  a39=(a38*a29);
  a37=(a37+a39);
  a39=(a37*a6);
  a33=(a33+a39);
  a39=cos(a4);
  a40=(a33*a39);
  a41=(a23*a32);
  a42=(a34*a41);
  a27=(a27*a6);
  a42=(a42-a27);
  a37=(a37*a32);
  a42=(a42+a37);
  a4=sin(a4);
  a42=(a42*a4);
  a40=(a40+a42);
  a40=(a20*a40);
  a33=(a20*a33);
  a42=-8.3000000000000004e-02;
  a34=(a42*a34);
  a37=-2.3990000000000000e-01;
  a27=(a37*a22);
  a43=5.0999999999999997e-02;
  a44=(a43*a28);
  a27=(a27+a44);
  a27=(a27+a0);
  a34=(a34+a27);
  a33=(a33+a34);
  a40=(a40+a33);
  if (res[0]!=0) res[0][24]=a40;
  a40=(a7*a13);
  a33=(a5*a10);
  a33=(a3*a33);
  a40=(a40+a33);
  a33=(a40*a25);
  a34=casadi_sq(a13);
  a27=casadi_sq(a5);
  a34=(a34+a27);
  a34=(a3*a34);
  a34=(a21-a34);
  a27=(a34*a16);
  a33=(a33-a27);
  a27=(a13*a10);
  a27=(a3*a27);
  a44=(a7*a5);
  a27=(a27-a44);
  a44=(a27*a31);
  a33=(a33+a44);
  a44=(a33*a32);
  a45=(a40*a26);
  a46=(a34*a24);
  a45=(a45-a46);
  a46=(a27*a30);
  a45=(a45+a46);
  a46=(a45*a35);
  a44=(a44+a46);
  a46=(a36*a34);
  a46=(a46-a40);
  a47=(a38*a27);
  a46=(a46+a47);
  a47=(a46*a6);
  a44=(a44+a47);
  a47=(a44*a39);
  a48=(a45*a41);
  a33=(a33*a6);
  a48=(a48-a33);
  a46=(a46*a32);
  a48=(a48+a46);
  a48=(a48*a4);
  a47=(a47+a48);
  a47=(a20*a47);
  a44=(a20*a44);
  a45=(a42*a45);
  a48=(a37*a40);
  a46=(a43*a34);
  a48=(a48+a46);
  a48=(a48+a1);
  a45=(a45+a48);
  a44=(a44+a45);
  a47=(a47+a44);
  if (res[0]!=0) res[0][25]=a47;
  a47=(a5*a13);
  a47=(a3*a47);
  a44=(a7*a10);
  a47=(a47-a44);
  a25=(a47*a25);
  a7=(a7*a5);
  a13=(a10*a13);
  a13=(a3*a13);
  a7=(a7+a13);
  a16=(a7*a16);
  a25=(a25-a16);
  a10=casadi_sq(a10);
  a5=casadi_sq(a5);
  a10=(a10+a5);
  a3=(a3*a10);
  a21=(a21-a3);
  a31=(a21*a31);
  a25=(a25+a31);
  a31=(a25*a32);
  a26=(a47*a26);
  a24=(a7*a24);
  a26=(a26-a24);
  a30=(a21*a30);
  a26=(a26+a30);
  a35=(a26*a35);
  a31=(a31+a35);
  a36=(a36*a7);
  a36=(a36-a47);
  a38=(a38*a21);
  a36=(a36+a38);
  a38=(a36*a6);
  a31=(a31+a38);
  a39=(a31*a39);
  a41=(a26*a41);
  a25=(a25*a6);
  a41=(a41-a25);
  a36=(a36*a32);
  a41=(a41+a36);
  a41=(a41*a4);
  a39=(a39+a41);
  a39=(a20*a39);
  a31=(a20*a31);
  a26=(a42*a26);
  a41=(a37*a47);
  a43=(a43*a7);
  a41=(a41+a43);
  a41=(a41+a2);
  a26=(a26+a41);
  a31=(a31+a26);
  a39=(a39+a31);
  if (res[0]!=0) res[0][26]=a39;
  a39=cos(a15);
  a31=(a23*a39);
  a26=(a22*a31);
  a15=sin(a15);
  a41=(a28*a15);
  a26=(a26+a41);
  a41=(a29*a39);
  a26=(a26-a41);
  a41=cos(a11);
  a43=(a26*a41);
  a4=(a28*a39);
  a36=(a23*a15);
  a32=(a22*a36);
  a4=(a4-a32);
  a32=(a29*a15);
  a4=(a4+a32);
  a11=sin(a11);
  a32=(a23*a11);
  a25=(a4*a32);
  a43=(a43+a25);
  a29=(a23*a29);
  a29=(a22+a29);
  a25=(a29*a11);
  a43=(a43-a25);
  a25=cos(a8);
  a6=(a43*a25);
  a38=(a23*a41);
  a35=(a4*a38);
  a26=(a26*a11);
  a35=(a35-a26);
  a29=(a29*a41);
  a35=(a35-a29);
  a8=sin(a8);
  a35=(a35*a8);
  a6=(a6+a35);
  a6=(a20*a6);
  a43=(a20*a43);
  a4=(a42*a4);
  a22=(a37*a22);
  a35=-5.0999999999999997e-02;
  a28=(a35*a28);
  a22=(a22+a28);
  a22=(a22+a0);
  a4=(a4+a22);
  a43=(a43+a4);
  a6=(a6+a43);
  if (res[0]!=0) res[0][27]=a6;
  a6=(a40*a31);
  a43=(a34*a15);
  a6=(a6+a43);
  a43=(a27*a39);
  a6=(a6-a43);
  a43=(a6*a41);
  a4=(a34*a39);
  a22=(a40*a36);
  a4=(a4-a22);
  a22=(a27*a15);
  a4=(a4+a22);
  a22=(a4*a32);
  a43=(a43+a22);
  a27=(a23*a27);
  a27=(a40+a27);
  a22=(a27*a11);
  a43=(a43-a22);
  a22=(a43*a25);
  a0=(a4*a38);
  a6=(a6*a11);
  a0=(a0-a6);
  a27=(a27*a41);
  a0=(a0-a27);
  a0=(a0*a8);
  a22=(a22+a0);
  a22=(a20*a22);
  a43=(a20*a43);
  a4=(a42*a4);
  a40=(a37*a40);
  a34=(a35*a34);
  a40=(a40+a34);
  a40=(a40+a1);
  a4=(a4+a40);
  a43=(a43+a4);
  a22=(a22+a43);
  if (res[0]!=0) res[0][28]=a22;
  a31=(a47*a31);
  a22=(a7*a15);
  a31=(a31+a22);
  a22=(a21*a39);
  a31=(a31-a22);
  a22=(a31*a41);
  a39=(a7*a39);
  a36=(a47*a36);
  a39=(a39-a36);
  a15=(a21*a15);
  a39=(a39+a15);
  a32=(a39*a32);
  a22=(a22+a32);
  a23=(a23*a21);
  a23=(a47+a23);
  a21=(a23*a11);
  a22=(a22-a21);
  a25=(a22*a25);
  a38=(a39*a38);
  a31=(a31*a11);
  a38=(a38-a31);
  a23=(a23*a41);
  a38=(a38-a23);
  a38=(a38*a8);
  a25=(a25+a38);
  a25=(a20*a25);
  a20=(a20*a22);
  a42=(a42*a39);
  a37=(a37*a47);
  a35=(a35*a7);
  a37=(a37+a35);
  a37=(a37+a2);
  a42=(a42+a37);
  a20=(a20+a42);
  a25=(a25+a20);
  if (res[0]!=0) res[0][29]=a25;
  a25=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][30]=a25;
  a25=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][31]=a25;
  a25=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][32]=a25;
  a25=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][33]=a25;
  a25=arg[1]? arg[1][4] : 0;
  if (res[0]!=0) res[0][34]=a25;
  a25=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][35]=a25;
  a25=arg[4]? arg[4][39] : 0;
  a20=arg[1]? arg[1][12] : 0;
  a25=(a25+a20);
  if (res[0]!=0) res[0][36]=a25;
  a20=arg[4]? arg[4][40] : 0;
  a42=arg[1]? arg[1][13] : 0;
  a20=(a20+a42);
  if (res[0]!=0) res[0][37]=a20;
  a42=arg[4]? arg[4][41] : 0;
  a37=arg[1]? arg[1][14] : 0;
  a42=(a42+a37);
  if (res[0]!=0) res[0][38]=a42;
  a37=arg[4]? arg[4][42] : 0;
  a2=arg[1]? arg[1][15] : 0;
  a37=(a37+a2);
  if (res[0]!=0) res[0][39]=a37;
  a2=arg[4]? arg[4][43] : 0;
  a35=arg[1]? arg[1][16] : 0;
  a2=(a2+a35);
  if (res[0]!=0) res[0][40]=a2;
  a35=arg[4]? arg[4][44] : 0;
  a7=arg[1]? arg[1][17] : 0;
  a35=(a35+a7);
  if (res[0]!=0) res[0][41]=a35;
  a7=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][42]=a7;
  a47=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][43]=a47;
  a39=arg[1]? arg[1][8] : 0;
  if (res[0]!=0) res[0][44]=a39;
  a22=arg[1]? arg[1][9] : 0;
  if (res[0]!=0) res[0][45]=a22;
  a38=arg[1]? arg[1][10] : 0;
  if (res[0]!=0) res[0][46]=a38;
  a8=arg[1]? arg[1][11] : 0;
  if (res[0]!=0) res[0][47]=a8;
  if (res[0]!=0) res[0][48]=a9;
  if (res[0]!=0) res[0][49]=a12;
  if (res[0]!=0) res[0][50]=a14;
  if (res[0]!=0) res[0][51]=a17;
  if (res[0]!=0) res[0][52]=a18;
  if (res[0]!=0) res[0][53]=a19;
  a19=0.;
  a18=5.0000000000000000e-01;
  a17=(a18*a42);
  a17=(a17+a25);
  a14=500.;
  a12=(a17-a14);
  a12=casadi_fmax(a19,a12);
  a17=(-a17);
  a12=casadi_fmax(a12,a17);
  if (res[0]!=0) res[0][54]=a12;
  a12=(a18*a42);
  a12=(a12-a25);
  a25=(a12-a14);
  a25=casadi_fmax(a19,a25);
  a12=(-a12);
  a25=casadi_fmax(a25,a12);
  if (res[0]!=0) res[0][55]=a25;
  a25=(a18*a42);
  a25=(a25+a20);
  a12=(a25-a14);
  a12=casadi_fmax(a19,a12);
  a25=(-a25);
  a12=casadi_fmax(a12,a25);
  if (res[0]!=0) res[0][56]=a12;
  a12=(a18*a42);
  a12=(a12-a20);
  a20=(a12-a14);
  a20=casadi_fmax(a19,a20);
  a12=(-a12);
  a20=casadi_fmax(a20,a12);
  if (res[0]!=0) res[0][57]=a20;
  a20=(a42-a14);
  a20=casadi_fmax(a19,a20);
  a42=(-a42);
  a20=casadi_fmax(a20,a42);
  if (res[0]!=0) res[0][58]=a20;
  a20=(a18*a35);
  a20=(a20+a37);
  a42=(a20-a14);
  a42=casadi_fmax(a19,a42);
  a20=(-a20);
  a42=casadi_fmax(a42,a20);
  if (res[0]!=0) res[0][59]=a42;
  a42=(a18*a35);
  a42=(a42-a37);
  a37=(a42-a14);
  a37=casadi_fmax(a19,a37);
  a42=(-a42);
  a37=casadi_fmax(a37,a42);
  if (res[0]!=0) res[0][60]=a37;
  a37=(a18*a35);
  a37=(a37+a2);
  a42=(a37-a14);
  a42=casadi_fmax(a19,a42);
  a37=(-a37);
  a42=casadi_fmax(a42,a37);
  if (res[0]!=0) res[0][61]=a42;
  a42=(a18*a35);
  a42=(a42-a2);
  a2=(a42-a14);
  a2=casadi_fmax(a19,a2);
  a42=(-a42);
  a2=casadi_fmax(a2,a42);
  if (res[0]!=0) res[0][62]=a2;
  a2=(a35-a14);
  a2=casadi_fmax(a19,a2);
  a35=(-a35);
  a2=casadi_fmax(a2,a35);
  if (res[0]!=0) res[0][63]=a2;
  a2=(a18*a39);
  a2=(a2+a7);
  a35=(a2-a14);
  a35=casadi_fmax(a19,a35);
  a2=(-a2);
  a35=casadi_fmax(a35,a2);
  if (res[0]!=0) res[0][64]=a35;
  a35=(a18*a39);
  a35=(a35-a7);
  a7=(a35-a14);
  a7=casadi_fmax(a19,a7);
  a35=(-a35);
  a7=casadi_fmax(a7,a35);
  if (res[0]!=0) res[0][65]=a7;
  a7=(a18*a39);
  a7=(a7+a47);
  a35=(a7-a14);
  a35=casadi_fmax(a19,a35);
  a7=(-a7);
  a35=casadi_fmax(a35,a7);
  if (res[0]!=0) res[0][66]=a35;
  a35=(a18*a39);
  a35=(a35-a47);
  a47=(a35-a14);
  a47=casadi_fmax(a19,a47);
  a35=(-a35);
  a47=casadi_fmax(a47,a35);
  if (res[0]!=0) res[0][67]=a47;
  a47=(a39-a14);
  a47=casadi_fmax(a19,a47);
  a39=(-a39);
  a47=casadi_fmax(a47,a39);
  if (res[0]!=0) res[0][68]=a47;
  a47=(a18*a8);
  a47=(a47+a22);
  a39=(a47-a14);
  a39=casadi_fmax(a19,a39);
  a47=(-a47);
  a39=casadi_fmax(a39,a47);
  if (res[0]!=0) res[0][69]=a39;
  a39=(a18*a8);
  a39=(a39-a22);
  a22=(a39-a14);
  a22=casadi_fmax(a19,a22);
  a39=(-a39);
  a22=casadi_fmax(a22,a39);
  if (res[0]!=0) res[0][70]=a22;
  a22=(a18*a8);
  a22=(a22+a38);
  a39=(a22-a14);
  a39=casadi_fmax(a19,a39);
  a22=(-a22);
  a39=casadi_fmax(a39,a22);
  if (res[0]!=0) res[0][71]=a39;
  a18=(a18*a8);
  a18=(a18-a38);
  a38=(a18-a14);
  a38=casadi_fmax(a19,a38);
  a18=(-a18);
  a38=casadi_fmax(a38,a18);
  if (res[0]!=0) res[0][72]=a38;
  a14=(a8-a14);
  a19=casadi_fmax(a19,a14);
  a8=(-a8);
  a19=casadi_fmax(a19,a8);
  if (res[0]!=0) res[0][73]=a19;
  return 0;
}

CASADI_SYMBOL_EXPORT int back_cost_y_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int back_cost_y_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int back_cost_y_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void back_cost_y_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int back_cost_y_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void back_cost_y_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void back_cost_y_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void back_cost_y_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int back_cost_y_fun_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int back_cost_y_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real back_cost_y_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* back_cost_y_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* back_cost_y_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* back_cost_y_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* back_cost_y_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int back_cost_y_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
