/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) back_constr_h_0_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};
static const casadi_int casadi_s1[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[55] = {51, 1, 0, 51, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50};
static const casadi_int casadi_s4[24] = {20, 1, 0, 20, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19};
static const casadi_int casadi_s5[59] = {43, 20, 0, 2, 4, 6, 8, 9, 11, 13, 15, 17, 18, 20, 22, 24, 26, 27, 29, 31, 33, 35, 36, 12, 14, 12, 14, 13, 14, 13, 14, 14, 15, 17, 15, 17, 16, 17, 16, 17, 17, 6, 8, 6, 8, 7, 8, 7, 8, 8, 9, 11, 9, 11, 10, 11, 10, 11, 11};
static const casadi_int casadi_s6[3] = {20, 0, 0};

/* back_constr_h_0_fun_jac_uxt_zt:(i0[25],i1[18],i2[],i3[51])->(o0[20],o1[43x20,36nz],o2[20x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
  a0=5.0000000000000000e-01;
  a1=arg[3]? arg[3][41] : 0;
  a2=arg[1]? arg[1][14] : 0;
  a1=(a1+a2);
  a2=(a0*a1);
  a3=arg[3]? arg[3][39] : 0;
  a4=arg[1]? arg[1][12] : 0;
  a3=(a3+a4);
  a2=(a2+a3);
  if (res[0]!=0) res[0][0]=a2;
  a2=(a0*a1);
  a2=(a2-a3);
  if (res[0]!=0) res[0][1]=a2;
  a2=(a0*a1);
  a3=arg[3]? arg[3][40] : 0;
  a4=arg[1]? arg[1][13] : 0;
  a3=(a3+a4);
  a2=(a2+a3);
  if (res[0]!=0) res[0][2]=a2;
  a2=(a0*a1);
  a2=(a2-a3);
  if (res[0]!=0) res[0][3]=a2;
  if (res[0]!=0) res[0][4]=a1;
  a1=arg[3]? arg[3][44] : 0;
  a2=arg[1]? arg[1][17] : 0;
  a1=(a1+a2);
  a2=(a0*a1);
  a3=arg[3]? arg[3][42] : 0;
  a4=arg[1]? arg[1][15] : 0;
  a3=(a3+a4);
  a2=(a2+a3);
  if (res[0]!=0) res[0][5]=a2;
  a2=(a0*a1);
  a2=(a2-a3);
  if (res[0]!=0) res[0][6]=a2;
  a2=(a0*a1);
  a3=arg[3]? arg[3][43] : 0;
  a4=arg[1]? arg[1][16] : 0;
  a3=(a3+a4);
  a2=(a2+a3);
  if (res[0]!=0) res[0][7]=a2;
  a2=(a0*a1);
  a2=(a2-a3);
  if (res[0]!=0) res[0][8]=a2;
  if (res[0]!=0) res[0][9]=a1;
  a1=arg[1]? arg[1][8] : 0;
  a2=(a0*a1);
  a3=arg[1]? arg[1][6] : 0;
  a2=(a2+a3);
  if (res[0]!=0) res[0][10]=a2;
  a2=(a0*a1);
  a2=(a2-a3);
  if (res[0]!=0) res[0][11]=a2;
  a2=(a0*a1);
  a3=arg[1]? arg[1][7] : 0;
  a2=(a2+a3);
  if (res[0]!=0) res[0][12]=a2;
  a2=(a0*a1);
  a2=(a2-a3);
  if (res[0]!=0) res[0][13]=a2;
  if (res[0]!=0) res[0][14]=a1;
  a1=arg[1]? arg[1][11] : 0;
  a2=(a0*a1);
  a3=arg[1]? arg[1][9] : 0;
  a2=(a2+a3);
  if (res[0]!=0) res[0][15]=a2;
  a2=(a0*a1);
  a2=(a2-a3);
  if (res[0]!=0) res[0][16]=a2;
  a2=(a0*a1);
  a3=arg[1]? arg[1][10] : 0;
  a2=(a2+a3);
  if (res[0]!=0) res[0][17]=a2;
  a2=(a0*a1);
  a2=(a2-a3);
  if (res[0]!=0) res[0][18]=a2;
  if (res[0]!=0) res[0][19]=a1;
  a1=1.;
  if (res[1]!=0) res[1][0]=a1;
  if (res[1]!=0) res[1][1]=a0;
  a2=-1.;
  if (res[1]!=0) res[1][2]=a2;
  if (res[1]!=0) res[1][3]=a0;
  if (res[1]!=0) res[1][4]=a1;
  if (res[1]!=0) res[1][5]=a0;
  if (res[1]!=0) res[1][6]=a2;
  if (res[1]!=0) res[1][7]=a0;
  if (res[1]!=0) res[1][8]=a1;
  if (res[1]!=0) res[1][9]=a1;
  if (res[1]!=0) res[1][10]=a0;
  if (res[1]!=0) res[1][11]=a2;
  if (res[1]!=0) res[1][12]=a0;
  if (res[1]!=0) res[1][13]=a1;
  if (res[1]!=0) res[1][14]=a0;
  if (res[1]!=0) res[1][15]=a2;
  if (res[1]!=0) res[1][16]=a0;
  if (res[1]!=0) res[1][17]=a1;
  if (res[1]!=0) res[1][18]=a1;
  if (res[1]!=0) res[1][19]=a0;
  if (res[1]!=0) res[1][20]=a2;
  if (res[1]!=0) res[1][21]=a0;
  if (res[1]!=0) res[1][22]=a1;
  if (res[1]!=0) res[1][23]=a0;
  if (res[1]!=0) res[1][24]=a2;
  if (res[1]!=0) res[1][25]=a0;
  if (res[1]!=0) res[1][26]=a1;
  if (res[1]!=0) res[1][27]=a1;
  if (res[1]!=0) res[1][28]=a0;
  if (res[1]!=0) res[1][29]=a2;
  if (res[1]!=0) res[1][30]=a0;
  if (res[1]!=0) res[1][31]=a1;
  if (res[1]!=0) res[1][32]=a0;
  if (res[1]!=0) res[1][33]=a2;
  if (res[1]!=0) res[1][34]=a0;
  if (res[1]!=0) res[1][35]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int back_constr_h_0_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int back_constr_h_0_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int back_constr_h_0_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void back_constr_h_0_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int back_constr_h_0_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void back_constr_h_0_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void back_constr_h_0_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void back_constr_h_0_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int back_constr_h_0_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int back_constr_h_0_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real back_constr_h_0_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* back_constr_h_0_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* back_constr_h_0_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* back_constr_h_0_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* back_constr_h_0_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int back_constr_h_0_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
